---
title: "qPCR_initial_exploration"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo=FALSE}
library(ggplot2)
library(gridExtra)

rm(list=ls())

load(file="../Coralphoto__Metadata/KI_Platy_metadataSH.RData")

ggplot(aes(y = S.H.log10, x = field_season), data = metadata.SH.noFQ) + geom_boxplot()
# ggplot(aes(y = S.H.log10, x = before.after), data = metadata.SH.noFQ) + geom_boxplot()
ggplot(aes(y = S.H, x = field_season), data = metadata.SH.noFQ) + geom_boxplot()


ggplot(aes(y = S.H.log10, x = field_season,color=dom), data = metadata.SH.noFQ) + geom_boxplot() + facet_wrap(~Status)

ggplot(aes(y = S.H.log10, x = field_season,color=dom), data = metadata.SH.noFQ) + geom_point() + facet_wrap(~Status)


ggplot(aes(y = S.H.log10, x = before.after,color=bleaching_proportion), data = metadata.SH.noFQ) + geom_point()

ggplot(aes(y = S.H.log10, x = bleaching_proportion,color=before.after), data = metadata.SH.noFQ) + geom_point()

ggplot(aes(y = S.H.log10, x = bleaching_proportion,color=before.after), data = metadata.SH.noFQ) + geom_point()

hist(metadata.SH$S.H,breaks = 100)

ggplot(aes(y = S.H.log10, x = date), data = metadata.SH.noFQ) + scale_x_datetime() + geom_smooth() + ggtitle("Symbiont:Host Ratio")

ggplot(aes(y = S.H.log10, x = date,color=dom), data = metadata.SH.noFQ) + geom_smooth() + facet_wrap(~Status) + ggtitle("Symbiont:Host Ratio")


metadata.SH.AD <- metadata.SH[which(metadata.SH$Status != "UK" & metadata.SH$Status != "gone" & metadata.SH$Status != "dead_or_gone"),]
metadata.SH.noFQ.AD <- metadata.SH.noFQ[which(metadata.SH.noFQ$Status != "UK" & metadata.SH.noFQ$Status != "gone" & metadata.SH.noFQ$Status != "dead_or_gone"),]
metadata.SH.noFQ.A <- metadata.SH.noFQ[which(metadata.SH.noFQ$Status != "UK" & metadata.SH.noFQ$Status != "gone" & metadata.SH.noFQ$Status != "dead_or_gone" & metadata.SH.noFQ$Status != "dead"),]

ggplot(aes(y = D.PaxC.log, x = C.PaxC.log,color=dom), data = metadata.SH.noFQ) + geom_point() + facet_wrap(~Status) + ggtitle("C:D")

ggplot(aes(y = D.PaxC.log, x = C.PaxC.log,color=before.after,shape=Status), data = metadata.SH.noFQ) + geom_point() + ggtitle("C:D")

ggplot(aes(y = D.PaxC.log, x = C.PaxC.log,shape=dom,color=field_season,group=coral_tag), data = metadata.SH.noFQ.A) + geom_point() + ggtitle("C:D") + xlim(-15,-2.5)+ ylim(-15,-2.5) + geom_line(aes(color=dom))+facet_wrap(~Status)

ggplot(aes(y = CtoD, x = date, group=coral_tag, color=Status), data = metadata.SH.noFQ) + scale_x_datetime() + geom_line() + ggtitle("Symbiont:Host Ratio") + geom_point(aes(color=dom))

metadata.SH.noFQ.99 <- metadata.SH.noFQ[which(metadata.SH.noFQ$coral_tag == 99),]
metadata.SH.noFQ.612 <- metadata.SH.noFQ[which(metadata.SH.noFQ$coral_tag == 612),]
metadata.SH.noFQ.754_899_1060 <- metadata.SH.noFQ[which(metadata.SH.noFQ$coral_tag == "754_899_1060"),]
metadata.SH.noFQ.792 <- metadata.SH.noFQ[which(metadata.SH.noFQ$coral_tag == 792),]
metadata.SH.noFQ.62 <- metadata.SH.noFQ[which(metadata.SH.noFQ$coral_tag == 62),]
metadata.SH.noFQ.328 <- metadata.SH.noFQ[which(metadata.SH.noFQ$coral_tag == 328),]
metadata.SH.noFQ.813 <- metadata.SH.noFQ[which(metadata.SH.noFQ$coral_tag == 813),]

ggplot(aes(y = D.PaxC.log, x = C.PaxC.log,shape=dom,color=field_season), data = metadata.SH.noFQ.99) + geom_point() + ggtitle("C:D") + geom_line(aes(color=dom))

ggplot(aes(y = S.H.log10, x = date), data = metadata.SH.noFQ.99) + geom_point(aes(color=dom)) + geom_line(linetype="dashed") + facet_wrap(~Status) + ggtitle("Symbiont:Host Ratio") + geom_point(aes(color=dom), data= metadata.SH.noFQ.612)+ geom_line(linetype="dotted", color="red", data= metadata.SH.noFQ.612)+ geom_point(aes(color=dom), data= metadata.SH.noFQ.754_899_1060)+ geom_line(linetype="dotdash",color="orange", data= metadata.SH.noFQ.754_899_1060)+ geom_point(aes(color=dom), data= metadata.SH.noFQ.792)+ geom_line(linetype="longdash",color="yellow", data= metadata.SH.noFQ.792)+ geom_point(aes(color=dom), data= metadata.SH.noFQ.62)+ geom_line(linetype="twodash",color="green", data= metadata.SH.noFQ.62)+ geom_point(aes(color=dom), data= metadata.SH.noFQ.328)+ geom_line(linetype="twodash", color="blue", data= metadata.SH.noFQ.328)

metadata.SH.noFQ.3plus <- metadata.SH.noFQ[which(table(metadata.SH.noFQ$coral_tag)>2),]

test <- metadata.SH.noFQ[ metadata.SH.noFQ$coral_tag %in%  names(table(metadata.SH.noFQ$coral_tag))[table(metadata.SH.noFQ$coral_tag) > 2] , ]
table(metadata.SH.noFQ.3plus$coral_tag)

metadata.SH.noFQ.AD.Cstart <- metadata.SH.noFQ.AD[which(metadata.SH.noFQ.AD$dom == "C"),]

ggplot(aes(y = S.H.log10, x = date,group=coral_tag), data = metadata.SH.noFQ.AD) + geom_point(aes(shape=Status, color=CtoD)) + scale_shape_manual(values=c(16,4)) + geom_line(linetype="dashed",color="darkgray") + ggtitle("Symbiont:Host Ratio") + geom_smooth(aes(y = S.H.log10, x = date, group=Status, color=..y..), span=.67, data = metadata.SH.noFQ.AD)+ scale_colour_gradient(low = "blue", high = "red")
  
ggplot(aes(y = S.H.log10, x = date,group=coral_tag), data = metadata.SH.noFQ.AD) + geom_point(aes(shape=Status, color=CtoD)) + scale_shape_manual(values=c(16,4)) + geom_line(linetype="dashed",color="darkgray") + ggtitle("Symbiont:Host Ratio") + geom_smooth(aes(y = S.H.log10, x = date, group=Status, color=..y..), span=.67, data = metadata.SH.noFQ.AD)+ scale_colour_gradient2(low = "blue", mid= "gray",high = "red", midpoint=1)

ggplot(aes(y = S.H.log10, x = date,group=coral_tag), data = metadata.SH.noFQ.AD) + geom_point(aes(shape=Status, color=CtoD)) + scale_shape_manual(values=c(16,4)) + geom_line(linetype="dashed",color="darkgray") + ggtitle("Symbiont:Host Ratio") + geom_smooth(aes(y = S.H.log10, x = date, group=Status, color=..y..), span=.67, data = metadata.SH.noFQ.AD)+ scale_colour_gradient2(low = "blue", mid= "gray",high = "red", midpoint=1)


min(metadata.SH.noFQ.AD$CtoD)
max(metadata.SH.noFQ$CtoD)
mean(metadata.SH.noFQ$CtoD)
median(metadata.SH.noFQ$CtoD)

ggplot(aes(y = S.H.log10, x = date), data = metadata.SH.noFQ.AD) 

ggplot(aes(y = D.PaxC.log, x = C.PaxC.log, color=CtoD, shape=Status), data = metadata.SH.noFQ.AD) + geom_point()  + ggtitle("C:D") + scale_colour_gradient2(low = "blue", mid= "yellow", high = "red", midpoint=4) + xlim(c(-15,-2)) + ylim(c(-15,-2))

ggplot(aes(y = D.PaxC.log, x = C.PaxC.log, color=dom, shape=Status), data = metadata.SH.noFQ.AD) + geom_point()  + ggtitle("C:D") + scale_color_manual(values=c("blue","red"))


#1b9e77
#d95f02
#7570b3

# C_col <- "#1b9e77" # or low = "#2166ac"
# D_col <- "#7570b3" # or high = "#b2182b"
C_col <- "#2166ac"
D_col <- "#b2182b"
stress_col <- "#d95f02"
stress_col <- "darkgoldenrod4"
stress_col <- "burlywood4"

scaletitle <- expression(paste("Dominant ", italic("Symbiodinium"), " Clade"))
p1 <- ggplot(aes(y = S.H.log10, x = date,group=coral_tag), data = metadata.SH.noFQ.AD)+
  geom_rect(aes(xmin = as.POSIXct("2015-07-01"), xmax = as.POSIXct("2016-05-01"), ymin = -Inf, ymax = Inf),fill = stress_col, alpha = 0.002) +
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(), 
        legend.position = c(0.75,0.15), 
        legend.direction = "horizontal",
        legend.text = element_blank(),
        legend.background = element_blank(),
        axis.text = element_text(size=12),
        axis.title = element_text(size=18)) +
  geom_point(aes(shape=Status, fill=dom),stroke=0,alpha=0.5, size=1.7) +
  scale_shape_manual(values=c(21,4),guide=FALSE) +
  scale_fill_manual(values=c(C_col,D_col),guide=FALSE) +
  geom_smooth(aes(y = S.H.log10, x = date, group=Status, color=..y..), 
              span=.67, data = metadata.SH.noFQ.AD,level = 0.9999) + 
  scale_colour_gradient2(low = C_col, high = D_col,mid="gray",midpoint = -5, 
                         name= scaletitle) + 
  ylab("Symbiont:Host Ratio") + xlab("") +
  scale_x_datetime(date_breaks = "4 months",date_labels = "%b-%Y",expand=c(0.01,0.01)) +
  guides(colour=guide_colourbar(title.position="top", title.hjust=0.5, barwidth=10))+
  annotate("text",x=as.POSIXct("2016-08-05"), y =-10.25,label="C")+
  annotate("text",x=as.POSIXct("2017-05-15"), y =-10.25,label="D")+
  annotate("text",x=as.POSIXct("2015-11-29"), y =-1.5,label="El Nino",size=6)+
  geom_vline(xintercept=as.numeric(as.POSIXct("2015-07-01")),linetype="dashed")+
  geom_vline(xintercept=as.numeric(as.POSIXct("2016-05-01")),linetype="dashed")

p1

p2 <- p1 +  geom_line(linetype="dashed",color="gray")
p2

scaletitle2 <- expression(paste(" Dominant ", italic("Symbiodinium"), " Clade"))
p3 <- ggplot(aes(y = D.PaxC.log, x = C.PaxC.log, color=dom, shape=Status), 
             data = metadata.SH.noFQ.AD) +
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        legend.position = c(0.81,0.87), 
        legend.direction = "horizontal",
        legend.background = element_rect(fill="white", color="black"),
        legend.key = element_blank(),
        legend.spacing.y = unit(0, "cm"),
        axis.text = element_text(size=12),
        axis.title = element_text(size=18)) + 
  geom_point(aes(shape=Status,fill=dom),stroke=0, alpha=0.7, size=2)  +
  scale_color_manual(values=c(C_col,D_col),name=scaletitle2, labels=c("clade C", "clade D")) + 
  scale_fill_manual(values=c(C_col,D_col),guide=FALSE) +
  scale_shape_manual(name="       Coral Status Post El Niño  ",
                     values = c(21,7),labels=c("Alive   ","Dead   ")) + 
  scale_x_continuous(expand=c(0.01,0.01), 
                     limits=c(min(metadata.SH.noFQ.AD$C.PaxC.log),
                              max(metadata.SH.noFQ.AD$C.PaxC.log,metadata.SH.noFQ.AD$D.PaxC.log)),
                     name="Clade C Abundance (log S:H)") +  
  scale_y_continuous(expand=c(0.01,0.01), 
                     limits=c(min(metadata.SH.noFQ.AD$C.PaxC.log),max(metadata.SH.noFQ.AD$C.PaxC.log,metadata.SH.noFQ.AD$D.PaxC.log)),
                     name="Clade D Abundance (log S:H)") +
  geom_abline(slope=1,intercept=0) + 
  guides(colour = guide_legend(title.position = "top",keywidth = 2.75, keyheight = 1.5,override.aes = list(size=8)))+ 
  guides(shape = guide_legend(title.position = "top",keywidth = 3.25, keyheight = 1.5,override.aes = list(size=8)))+
  annotate("text",x=-14.5, y =-13.8,label="Coral is dominated by clade D",angle=40,color=D_col)+
  annotate("text",x=-14, y =-14.5,label="Coral is dominated by clade C",angle=40, color= C_col)


grid.arrange(p1,p3,nrow=1,ncol=2)


grid.arrange(p2,p3,nrow=1,ncol=2)

# 
# x=seq(-16,-4,0.1)
# y=seq(-16,-4,0.1)
# dat = data.frame(x=x, y=y)
# dat$ymax=max(dat$y)
# 
# ggplot(dat)+geom_ribbon(aes(x, ymin=y, ymax=ymax), fill="blue",data = dat)

C_col <- "darkgray"
D_col <- "gray40"

p3.2 <- ggplot(aes(y = D.PaxC.log, x = C.PaxC.log, color=Year_Pre_Post, shape=Status), 
             data = metadata.SH.noFQ.AD) +
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        legend.position = "bottom", #c(0.81,0.87), 
        legend.direction = "horizontal",
        legend.background = element_rect(fill="white", color="black"),
        legend.key = element_blank(),
        legend.spacing.y = unit(0, "cm"),
        axis.text = element_text(size=12),
        axis.title = element_text(size=18)) + 
  geom_point(aes(shape=Status,fill=dom),stroke=0, alpha=0.7, size=3)  +
  scale_color_manual(values=c("red","darkorange","green","purple","turquoise"),name=scaletitle2) + 
  scale_fill_manual(values=c(C_col,D_col),guide=FALSE) +
  scale_shape_manual(name="       Coral Status (March 2016)  ",
                     values = c(21,7),labels=c("Alive   ","Dead   ")) + 
  scale_x_continuous(expand=c(0.01,0.01), 
                     limits=c(min(metadata.SH.noFQ.AD$C.PaxC.log),
                              max(metadata.SH.noFQ.AD$C.PaxC.log,metadata.SH.noFQ.AD$D.PaxC.log)),
                     name="Clade C Abundance (log S:H)") +  
  scale_y_continuous(expand=c(0.01,0.01), 
                     limits=c(min(metadata.SH.noFQ.AD$C.PaxC.log),max(metadata.SH.noFQ.AD$C.PaxC.log,metadata.SH.noFQ.AD$D.PaxC.log)),
                     name="Clade D Abundance (log S:H)") +
  geom_abline(slope=1,intercept=0) + 
  guides(colour = guide_legend(title.position = "top",keywidth = 2.75, keyheight = 1.5))+ 
  guides(shape = guide_legend(title.position = "top",keywidth = 3.25, keyheight = 1.5))+
  annotate("text",x=-14.5, y =-13.8,label="clade D",angle=40,color=D_col)+
  annotate("text",x=-14, y =-14.5,label="clade C",angle=40, color= C_col)

str(metadata.SH.noFQ.AD$Year_Pre_Post)
metadata.SH.noFQ.AD.Ordered <- metadata.SH.noFQ.AD[order(metadata.SH.noFQ.AD$Year_Pre_Post),]
p4 <- p3.2 + geom_path(aes(group=coral_tag,color=Year_Pre_Post),arrow=arrow(length=unit(0.30,"cm"), type = "closed"), data = metadata.SH.noFQ.AD.Ordered)
p4

p4.2 <- p4 + facet_wrap(~Year_Pre_Post)
p4.2

p4.3 <- p4 + scale_color_manual(values=c("red","darkorange","lightgray","lightgray","lightgray"),name=scaletitle2)
p4.3

metadata.SH.noFQ.AD.Ordered.15bto15c <- metadata.SH.noFQ.AD.Ordered[which(metadata.SH.noFQ.AD.Ordered$field_season == "KI2015b" | metadata.SH.noFQ.AD.Ordered$field_season == "KI2015c"),]
metadata.SH.noFQ.AD.Ordered.15cto16a <- metadata.SH.noFQ.AD.Ordered[which(metadata.SH.noFQ.AD.Ordered$field_season == "KI2015c" | metadata.SH.noFQ.AD.Ordered$field_season == "KI2016a"),]
metadata.SH.noFQ.AD.Ordered.16ato16b <- metadata.SH.noFQ.AD.Ordered[which(metadata.SH.noFQ.AD.Ordered$field_season == "KI2016a" | metadata.SH.noFQ.AD.Ordered$field_season == "KI2016b"),]
metadata.SH.noFQ.AD.Ordered.16bto17a <- metadata.SH.noFQ.AD.Ordered[which(metadata.SH.noFQ.AD.Ordered$field_season == "KI2016b" | metadata.SH.noFQ.AD.Ordered$field_season == "KI2017a"),]


p5 <- p3.2 + geom_path(aes(group=coral_tag,color=Year_Pre_Post),arrow=arrow(length=unit(0.30,"cm"), type = "closed"), data = metadata.SH.noFQ.AD.Ordered.15bto15c)+ theme(legend.position="none") + scale_color_manual(values=c("red","darkorange","white","white","white"))+ scale_fill_manual(values=c("white","white"))
p5.2 <- p3.2 + geom_path(aes(group=coral_tag,color=Year_Pre_Post),arrow=arrow(length=unit(0.30,"cm"), type = "closed"), data = metadata.SH.noFQ.AD.Ordered.15cto16a)+ theme(legend.position="none")+ scale_color_manual(values=c("white","darkorange","green","white","white"))+ scale_fill_manual(values=c("white","white"))
p5.3 <- p3.2 + geom_path(aes(group=coral_tag,color=Year_Pre_Post),arrow=arrow(length=unit(0.30,"cm"), type = "closed"), data = metadata.SH.noFQ.AD.Ordered.16ato16b)+ theme(legend.position="none")+ scale_color_manual(values=c("white","white","green","purple","white"))+ scale_fill_manual(values=c("white","white"))
p5.4 <- p3.2 + geom_path(aes(group=coral_tag,color=Year_Pre_Post),arrow=arrow(length=unit(0.30,"cm"), type = "closed"), data = metadata.SH.noFQ.AD.Ordered.16bto17a)+ theme(legend.position="none")+ scale_color_manual(values=c("white","white","white","purple","turquoise"))+ scale_fill_manual(values=c("white","white"))

grid.arrange(p5,p5.2,p5.3,p5.4,nrow=1,ncol=4)

head(metadata.SH.noFQ)

Dmean <- aggregate(x=metadata.SH.noFQ$D.PaxC.log10,
          by=list(Year_Pre_Post = metadata.SH.noFQ$Year_Pre_Post),
          FUN = mean)
colnames(Dmean) <- c("Year_Pre_Post","D.PaxC.log10")
Dstd <- aggregate(x=metadata.SH.noFQ$D.PaxC.log10,
          by=list(Year_Pre_Post = metadata.SH.noFQ$Year_Pre_Post),
          FUN = sd)
colnames(Dstd) <- c("Year_Pre_Post","D.PaxC.log10.std")

Cmean <- aggregate(x=metadata.SH.noFQ$C.PaxC.log10,
          by=list(Year_Pre_Post = metadata.SH.noFQ$Year_Pre_Post),
          FUN = mean)
colnames(Cmean) <- c("Year_Pre_Post","C.PaxC.log10")
Cstd <- aggregate(x=metadata.SH.noFQ$C.PaxC.log10,
          by=list(Year_Pre_Post = metadata.SH.noFQ$Year_Pre_Post),
          FUN = sd)
colnames(Cstd) <- c("Year_Pre_Post","C.PaxC.log10.std")

CD.PaxC.log10mean <- merge(Dmean,Cmean)
CD.PaxC.log10std <- merge(Dstd,Cstd)
CD.PaxC.log10 <- merge(CD.PaxC.log10mean,CD.PaxC.log10std)


ggplot(aes(x=C.PaxC.log10, y=D.PaxC.log10,color=Year_Pre_Post),data=CD.PaxC.log10)+
  geom_point()+
  geom_errorbar(aes(ymin=D.PaxC.log10-D.PaxC.log10.std, ymax=D.PaxC.log10+D.PaxC.log10.std), width=.1)+
  geom_errorbarh(aes(xmin=C.PaxC.log10-C.PaxC.log10.std, xmax=C.PaxC.log10+C.PaxC.log10.std), height=.1)+
  geom_point(data=metadata.SH.noFQ, aes(x=C.PaxC.log10,y=D.PaxC.log10,color=Year_Pre_Post))



Dmean2 <- aggregate(x=metadata.SH.noFQ.AD$D.PaxC.log10,
          by=list(Year_Pre_Post = metadata.SH.noFQ.AD$Year_Pre_Post, Status=metadata.SH.noFQ.AD$Status),
          FUN = mean)
colnames(Dmean2) <- c("Year_Pre_Post","Status","D.PaxC.log10")
Dstd2 <- aggregate(x=metadata.SH.noFQ.AD$D.PaxC.log10,
          by=list(Year_Pre_Post = metadata.SH.noFQ.AD$Year_Pre_Post, Status=metadata.SH.noFQ.AD$Status),
          FUN = sd)
colnames(Dstd2) <- c("Year_Pre_Post","Status","D.PaxC.log10.std")

Cmean2 <- aggregate(x=metadata.SH.noFQ.AD$C.PaxC.log10,
          by=list(Year_Pre_Post = metadata.SH.noFQ.AD$Year_Pre_Post, Status=metadata.SH.noFQ.AD$Status),
          FUN = mean)
colnames(Cmean2) <- c("Year_Pre_Post","Status","C.PaxC.log10")
Cstd2 <- aggregate(x=metadata.SH.noFQ.AD$C.PaxC.log10,
          by=list(Year_Pre_Post = metadata.SH.noFQ.AD$Year_Pre_Post, Status=metadata.SH.noFQ.AD$Status),
          FUN = sd)
Cse2 <- aggregate(x=metadata.SH.noFQ.AD$C.PaxC.log10,
          by=list(Year_Pre_Post = metadata.SH.noFQ.AD$Year_Pre_Post, Status=metadata.SH.noFQ.AD$Status),
          FUN = sd)
colnames(Cstd2) <- c("Year_Pre_Post","Status","C.PaxC.log10.std")

CD.PaxC.log10mean2 <- merge(Dmean2,Cmean2)
CD.PaxC.log10std2 <- merge(Dstd2,Cstd2)
CD.PaxC.log10_2 <- merge(CD.PaxC.log10mean2,CD.PaxC.log10std2)

ggplot(aes(x=C.PaxC.log10,
           y=D.PaxC.log10,color=Year_Pre_Post,
           group=Status,shape=Status),
       data=CD.PaxC.log10_2)+
  geom_point()+
  geom_errorbar(aes(ymin=D.PaxC.log10-D.PaxC.log10.std, ymax=D.PaxC.log10+D.PaxC.log10.std,
                    linetype=Status,alpha=0.2), width=.1,show.legend = FALSE)+
  geom_errorbarh(aes(xmin=C.PaxC.log10-C.PaxC.log10.std, xmax=C.PaxC.log10+C.PaxC.log10.std,
                     linetype=Status,alpha=0.2), height=.1,show.legend = FALSE)+
  geom_path(arrow=arrow(length=unit(0.30,"cm"), type = "closed"))+
  geom_point(data=metadata.SH.noFQ.AD, aes(x=C.PaxC.log10,y=D.PaxC.log10,color=Year_Pre_Post,shape=Status))


```


```{r, echo=FALSE}

p1 <- ggplot(aes(x = S.H, fill=field_season), data = metadata.SH.noFQ) + 
  theme(legend.position = c(0.9,0.7)) +
  geom_histogram() + 
  # facet_grid(. ~ field_season) +
  scale_fill_manual(values=c("#2b83ba","#abdda4","#e6f598","#fdae61","#d7191c"),name ="Field Season") +
  ylab("Count") +
  xlab("Symbiont:Host Ratio")
p1  
# xlim(0,0.1)

p2 <- ggplot(aes(x = S.H, fill=field_season), data = metadata.SH.noFQ) + 
  # facet_grid(. ~ field_season) +
  scale_fill_manual(values=c("#2b83ba","#abdda4","#e6f598","#fdae61","#d7191c")) +
  geom_density(aes(x = S.H), alpha=0.5) +  
  guides(fill=FALSE) +
  ylab("Density") +
  xlab("Symbiont:Host Ratio")
  # xlim(0,0.1)

p3 <- ggplot(aes(x = S.H, fill=field_season), data = metadata.SH.noFQ) + 
    facet_grid(. ~ field_season) +
  theme(axis.text.x = element_text(size=8))+
  geom_density(aes(x = S.H, fill="lightgray"), alpha=0.5) + 
  geom_histogram(color="black") + 
  scale_fill_manual(values=c("#2b83ba","#abdda4","#e6f598","#fdae61","#d7191c", "lightgray")) +
  guides(fill=FALSE) + 
  scale_x_continuous("Symbiont:Host Ratio", breaks=c(0,0.02,0.04,0.06,0.08,0.10),labels=c("0","0.02","0.04","0.06","0.08","0.10"),limits = c(0,0.1)) +
  ylab("Density
Count")

jpeg(file="raw_SH_hist.jpg",width=10, height=8,units="in", res=300)
grid.arrange(p1,p2,p3)
dev.off()


p4 <- ggplot(aes(x = S.H, y=C.PaxC, fill=bleaching_proportion, col=dom), data = metadata.SH.noFQ) + 
  theme(legend.position = c(0.9,0.7)) +
  # facet_grid(. ~ bleaching_proportion) +
  geom_point(aes(x = S.H, y=C.PaxC)) +
  scale_fill_manual(values=c("orange","red","blue")) +
  geom_density_2d(aes(x = S.H, y=C.PaxC), alpha=0.5) +  
  # guides(fill=FALSE) +
  xlab("Symbiont:Host Ratio")
  # xlim(0,0.1)
p4

p5 <- ggplot(aes(x = S.H, fill=field_season), data = metadata.SH.noFQ) + 
  facet_grid(. ~ bleaching_proportion) +
  scale_fill_manual(values=c("#2b83ba","#abdda4","#e6f598","#fdae61","#d7191c")) +
  # geom_density(aes(x = S.H), alpha=0.5) + 
  geom_histogram(position="dodge") +
  # guides(fill=FALSE) +
  xlab("Symbiont:Host Ratio") +
  xlim(0,0.08)
p5
```

