#!/bin/bash
set -e
set -u
set -o pipefail

iu-merge-pairs -o  KI14FSYM004 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI14FSYM004
iu-merge-pairs -o  KI14FSYM019 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI14FSYM019
iu-merge-pairs -o  KI14FSYM029 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI14FSYM029
iu-merge-pairs -o  KI14FSYM062 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI14FSYM062
iu-merge-pairs -o  KI14FSYM089 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI14FSYM089
iu-merge-pairs -o  KI14FSYM099 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI14FSYM099
iu-merge-pairs -o  KI14FSYM100 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI14FSYM100
iu-merge-pairs -o  KI14FSYM127 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI14FSYM127
iu-merge-pairs -o  KI14FSYM146 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI14FSYM146
iu-merge-pairs -o  KI14FSYM148 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI14FSYM148
iu-merge-pairs -o  KI14FSYM157 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI14FSYM157
iu-merge-pairs -o  KI14FSYM161 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI14FSYM161
iu-merge-pairs -o  KI14FSYM164 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI14FSYM164
iu-merge-pairs -o  KI14FSYM192 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI14FSYM192
iu-merge-pairs -o  KI14FSYM205 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI14FSYM205
iu-merge-pairs -o  KI14FSYM213 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI14FSYM213
iu-merge-pairs -o  KI14FSYM223 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI14FSYM223
iu-merge-pairs -o  KI14FSYM231 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI14FSYM231
iu-merge-pairs -o  KI14FSYM234 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI14FSYM234
iu-merge-pairs -o  KI14FSYM242 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI14FSYM242
iu-merge-pairs -o  KI14FSYM245 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI14FSYM245
iu-merge-pairs -o  KI14FSYM248 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI14FSYM248
iu-merge-pairs -o  KI14FSYM249 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI14FSYM249
iu-merge-pairs -o  KI14FSYM253 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI14FSYM253
iu-merge-pairs -o  KI14FSYM258 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI14FSYM258
iu-merge-pairs -o  KI14FSYM266 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI14FSYM266
iu-merge-pairs -o  KI14FSYM271 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI14FSYM271
iu-merge-pairs -o  KI14FSYM273 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI14FSYM273
iu-merge-pairs -o  KI14FSYM278 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI14FSYM278
iu-merge-pairs -o  KI14FSYM285 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI14FSYM285
iu-merge-pairs -o  KI14FSYM289 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI14FSYM289
iu-merge-pairs -o  KI14FSYM298 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI14FSYM298
iu-merge-pairs -o  KI14FSYM299 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI14FSYM299
iu-merge-pairs -o  KI14FSYM306 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI14FSYM306
iu-merge-pairs -o  KI14FSYM311 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI14FSYM311
iu-merge-pairs -o  KI14FSYM328 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI14FSYM328
iu-merge-pairs -o  KI14FSYM334 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI14FSYM334
iu-merge-pairs -o  KI14FSYM338 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI14FSYM338
iu-merge-pairs -o  KI14FSYM339 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI14FSYM339
iu-merge-pairs -o  KI14FSYM341 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI14FSYM341
iu-merge-pairs -o  KI14FSYM351 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI14FSYM351
iu-merge-pairs -o  KI14FSYM352 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI14FSYM352
iu-merge-pairs -o  KI14FSYM353 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI14FSYM353
iu-merge-pairs -o  KI14FSYM371 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI14FSYM371
iu-merge-pairs -o  KI14FSYM373 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI14FSYM373
iu-merge-pairs -o  KI14FSYM379 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI14FSYM379
iu-merge-pairs -o  KI14FSYM386 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI14FSYM386
iu-merge-pairs -o  KI14FSYM388 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI14FSYM388
iu-merge-pairs -o  KI14FSYM389 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI14FSYM389
iu-merge-pairs -o  KI14FSYM400 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI14FSYM400
iu-merge-pairs -o  KI14FSYM402 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI14FSYM402
iu-merge-pairs -o  KI14FSYM410 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI14FSYM410
iu-merge-pairs -o  KI14FSYM412 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI14FSYM412
iu-merge-pairs -o  KI14FSYM435 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI14FSYM435
iu-merge-pairs -o  KI14FSYM439 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI14FSYM439
iu-merge-pairs -o  KI14FSYM442 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI14FSYM442
iu-merge-pairs -o  KI14FSYM447 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI14FSYM447
iu-merge-pairs -o  KI14FSYM449 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI14FSYM449
iu-merge-pairs -o  KI14FSYM454 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI14FSYM454
iu-merge-pairs -o  KI14FSYM455 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI14FSYM455
iu-merge-pairs -o  KI14FSYM461 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI14FSYM461
iu-merge-pairs -o  KI14FSYM466 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI14FSYM466
iu-merge-pairs -o  KI14FSYM470 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI14FSYM470
iu-merge-pairs -o  KI14FSYM473 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI14FSYM473
iu-merge-pairs -o  KI14FSYM479 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI14FSYM479
iu-merge-pairs -o  KI14FSYM482 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI14FSYM482
iu-merge-pairs -o  KI14FSYM486 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI14FSYM486
iu-merge-pairs -o  KI14FSYM487 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI14FSYM487
iu-merge-pairs -o  KI14FSYM492 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI14FSYM492
iu-merge-pairs -o  KI14FSYM497 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI14FSYM497
iu-merge-pairs -o  KI14FSYM500 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI14FSYM500
iu-merge-pairs -o  KI14FSYM504 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI14FSYM504
iu-merge-pairs -o  KI15aFSYM002 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15aFSYM002
iu-merge-pairs -o  KI15aFSYM014 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15aFSYM014
iu-merge-pairs -o  KI15aFSYM015 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15aFSYM015
iu-merge-pairs -o  KI15aFSYM032 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15aFSYM032
iu-merge-pairs -o  KI15aFSYM037 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15aFSYM037
iu-merge-pairs -o  KI15aFSYM041 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15aFSYM041
iu-merge-pairs -o  KI15aFSYM043 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15aFSYM043
iu-merge-pairs -o  KI15aFSYM046 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15aFSYM046
iu-merge-pairs -o  KI15aFSYM052 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15aFSYM052
iu-merge-pairs -o  KI15aFSYM057 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15aFSYM057
iu-merge-pairs -o  KI15aFSYM067 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15aFSYM067
iu-merge-pairs -o  KI15aFSYM072 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15aFSYM072
iu-merge-pairs -o  KI15aFSYM077 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15aFSYM077
iu-merge-pairs -o  KI15aFSYM081 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15aFSYM081
iu-merge-pairs -o  KI15aFSYM096 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15aFSYM096
iu-merge-pairs -o  KI15aFSYM097 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15aFSYM097
iu-merge-pairs -o  KI15aFSYM103 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15aFSYM103
iu-merge-pairs -o  KI15aFSYM105 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15aFSYM105
iu-merge-pairs -o  KI15aFSYM113 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15aFSYM113
iu-merge-pairs -o  KI15aFSYM116 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15aFSYM116
iu-merge-pairs -o  KI15aFSYM123 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15aFSYM123
iu-merge-pairs -o  KI15aFSYM139 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15aFSYM139
iu-merge-pairs -o  KI15aFSYM145 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15aFSYM145
iu-merge-pairs -o  KI15aFSYM150 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15aFSYM150
iu-merge-pairs -o  KI15aFSYM156 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15aFSYM156
iu-merge-pairs -o  KI15aFSYM160 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15aFSYM160
iu-merge-pairs -o  KI15aFSYM163 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15aFSYM163
iu-merge-pairs -o  KI15bFSYM002 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15bFSYM002
iu-merge-pairs -o  KI15bFSYM015 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15bFSYM015
iu-merge-pairs -o  KI15bFSYM019 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15bFSYM019
iu-merge-pairs -o  KI15bFSYM020 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15bFSYM020
iu-merge-pairs -o  KI15bFSYM023 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15bFSYM023
iu-merge-pairs -o  KI15bFSYM026 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15bFSYM026
iu-merge-pairs -o  KI15bFSYM038 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15bFSYM038
iu-merge-pairs -o  KI15bFSYM050 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15bFSYM050
iu-merge-pairs -o  KI15bFSYM057 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15bFSYM057
iu-merge-pairs -o  KI15bFSYM065 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15bFSYM065
iu-merge-pairs -o  KI15bFSYM068 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15bFSYM068
iu-merge-pairs -o  KI15bFSYM069 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15bFSYM069
iu-merge-pairs -o  KI15bFSYM080 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15bFSYM080
iu-merge-pairs -o  KI15bFSYM084 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15bFSYM084
iu-merge-pairs -o  KI15bFSYM088 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15bFSYM088
iu-merge-pairs -o  KI15bFSYM092 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15bFSYM092
iu-merge-pairs -o  KI15bFSYM102 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15bFSYM102
iu-merge-pairs -o  KI15bFSYM131 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15bFSYM131
iu-merge-pairs -o  KI15bFSYM132 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15bFSYM132
iu-merge-pairs -o  KI15bFSYM138 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15bFSYM138
iu-merge-pairs -o  KI15bFSYM140 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15bFSYM140
iu-merge-pairs -o  KI15bFSYM147 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15bFSYM147
iu-merge-pairs -o  KI15bFSYM164 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15bFSYM164
iu-merge-pairs -o  KI15bFSYM167 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15bFSYM167
iu-merge-pairs -o  KI15bFSYM179 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15bFSYM179
iu-merge-pairs -o  KI15bFSYM184 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15bFSYM184
iu-merge-pairs -o  KI15bFSYM187 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15bFSYM187
iu-merge-pairs -o  KI15bFSYM188 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15bFSYM188
iu-merge-pairs -o  KI15bFSYM191 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15bFSYM191
iu-merge-pairs -o  KI15bFSYM194 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15bFSYM194
iu-merge-pairs -o  KI15bFSYM197 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15bFSYM197
iu-merge-pairs -o  KI15bFSYM200 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15bFSYM200
iu-merge-pairs -o  KI15bFSYM204 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15bFSYM204
iu-merge-pairs -o  KI15bFSYM205 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15bFSYM205
iu-merge-pairs -o  KI15bFSYM207 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15bFSYM207
iu-merge-pairs -o  KI15bFSYM213 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15bFSYM213
iu-merge-pairs -o  KI15bFSYM214 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15bFSYM214
iu-merge-pairs -o  KI15bFSYM216 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15bFSYM216
iu-merge-pairs -o  KI15bFSYM218 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15bFSYM218
iu-merge-pairs -o  KI15bFSYM219 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15bFSYM219
iu-merge-pairs -o  KI15bFSYM231 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15bFSYM231
iu-merge-pairs -o  KI15bFSYM239 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15bFSYM239
iu-merge-pairs -o  KI15bFSYM243 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15bFSYM243
iu-merge-pairs -o  KI15bFSYM245 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15bFSYM245
iu-merge-pairs -o  KI15bFSYM247 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15bFSYM247
iu-merge-pairs -o  KI15bFSYM249 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15bFSYM249
iu-merge-pairs -o  KI15bFSYM255 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15bFSYM255
iu-merge-pairs -o  KI15bFSYM259 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15bFSYM259
iu-merge-pairs -o  KI15bFSYM263 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15bFSYM263
iu-merge-pairs -o  KI15bFSYM277 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15bFSYM277
iu-merge-pairs -o  KI15bFSYM279 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15bFSYM279
iu-merge-pairs -o  KI15bFSYM282 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15bFSYM282
iu-merge-pairs -o  KI15bFSYM283 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15bFSYM283
iu-merge-pairs -o  KI15bFSYM284 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15bFSYM284
iu-merge-pairs -o  KI15bFSYM288 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15bFSYM288
iu-merge-pairs -o  KI15bFSYM293 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15bFSYM293
iu-merge-pairs -o  KI15bFSYM296 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15bFSYM296
iu-merge-pairs -o  KI15bFSYM303 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15bFSYM303
iu-merge-pairs -o  KI15bFSYM306 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15bFSYM306
iu-merge-pairs -o  KI15bFSYM309 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15bFSYM309
iu-merge-pairs -o  KI15bFSYM313 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15bFSYM313
iu-merge-pairs -o  KI15bFSYM316 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15bFSYM316
iu-merge-pairs -o  KI15bFSYM320 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15bFSYM320
iu-merge-pairs -o  KI15bFSYM340 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15bFSYM340
iu-merge-pairs -o  KI15bFSYM346 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15bFSYM346
iu-merge-pairs -o  KI15bFSYM352 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15bFSYM352
iu-merge-pairs -o  KI15bFSYM353 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15bFSYM353
iu-merge-pairs -o  KI15cFSYM003 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15cFSYM003
iu-merge-pairs -o  KI15cFSYM014 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15cFSYM014
iu-merge-pairs -o  KI15cFSYM018 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15cFSYM018
iu-merge-pairs -o  KI15cFSYM025 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15cFSYM025
iu-merge-pairs -o  KI15cFSYM063 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15cFSYM063
iu-merge-pairs -o  KI15cFSYM064 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15cFSYM064
iu-merge-pairs -o  KI15cFSYM065 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15cFSYM065
iu-merge-pairs -o  KI15cFSYM072 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15cFSYM072
iu-merge-pairs -o  KI15cFSYM077 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15cFSYM077
iu-merge-pairs -o  KI15cFSYM082 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15cFSYM082
iu-merge-pairs -o  KI15cFSYM083 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15cFSYM083
iu-merge-pairs -o  KI15cFSYM090 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15cFSYM090
iu-merge-pairs -o  KI15cFSYM094 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15cFSYM094
iu-merge-pairs -o  KI15cFSYM101 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15cFSYM101
iu-merge-pairs -o  KI15cFSYM104 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15cFSYM104
iu-merge-pairs -o  KI15cFSYM112 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15cFSYM112
iu-merge-pairs -o  KI15cFSYM114 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15cFSYM114
iu-merge-pairs -o  KI15cFSYM116 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15cFSYM116
iu-merge-pairs -o  KI15cFSYM125 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15cFSYM125
iu-merge-pairs -o  KI15cFSYM126 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15cFSYM126
iu-merge-pairs -o  KI15cFSYM129 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15cFSYM129
iu-merge-pairs -o  KI15cFSYM142 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15cFSYM142
iu-merge-pairs -o  KI15cFSYM144 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15cFSYM144
iu-merge-pairs -o  KI15cFSYM145 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15cFSYM145
iu-merge-pairs -o  KI15cFSYM159 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15cFSYM159
iu-merge-pairs -o  KI15cFSYM161 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15cFSYM161
iu-merge-pairs -o  KI15cFSYM171 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15cFSYM171
iu-merge-pairs -o  KI15cFSYM178 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15cFSYM178
iu-merge-pairs -o  KI15cFSYM180 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15cFSYM180
iu-merge-pairs -o  KI15cFSYM190 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15cFSYM190
iu-merge-pairs -o  KI15cFSYM200 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15cFSYM200
iu-merge-pairs -o  KI15cFSYM209 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15cFSYM209
iu-merge-pairs -o  KI15cFSYM216 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15cFSYM216
iu-merge-pairs -o  KI15cFSYM225 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15cFSYM225
iu-merge-pairs -o  KI15cFSYM252 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15cFSYM252
iu-merge-pairs -o  KI15cFSYM253 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15cFSYM253
iu-merge-pairs -o  KI15cFSYM254 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15cFSYM254
iu-merge-pairs -o  KI15cFSYM261 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15cFSYM261
iu-merge-pairs -o  KI15cFSYM265 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15cFSYM265
iu-merge-pairs -o  KI15cFSYM273 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15cFSYM273
iu-merge-pairs -o  KI15cFSYM275 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15cFSYM275
iu-merge-pairs -o  KI15cFSYM276 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15cFSYM276
iu-merge-pairs -o  KI15cFSYM277 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15cFSYM277
iu-merge-pairs -o  KI15cFSYM278 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15cFSYM278
iu-merge-pairs -o  KI15cFSYM283 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15cFSYM283
iu-merge-pairs -o  KI15cFSYM317 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15cFSYM317
iu-merge-pairs -o  KI15cFSYM328 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15cFSYM328
iu-merge-pairs -o  KI15cFSYM336 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15cFSYM336
iu-merge-pairs -o  KI15cFSYM338 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15cFSYM338
iu-merge-pairs -o  KI15cFSYM345 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15cFSYM345
iu-merge-pairs -o  KI15cFSYM348 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15cFSYM348
iu-merge-pairs -o  KI15cFSYM350 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15cFSYM350
iu-merge-pairs -o  KI15cFSYM365 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15cFSYM365
iu-merge-pairs -o  KI15cFSYM372 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15cFSYM372
iu-merge-pairs -o  KI15cFSYM373 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15cFSYM373
iu-merge-pairs -o  KI15cFSYM385 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15cFSYM385
iu-merge-pairs -o  KI15cFSYM399 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15cFSYM399
iu-merge-pairs -o  KI15cFSYM404 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15cFSYM404
iu-merge-pairs -o  KI15cFSYM411 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15cFSYM411
iu-merge-pairs -o  KI15cFSYM415 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15cFSYM415
iu-merge-pairs -o  KI15cFSYM427 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15cFSYM427
iu-merge-pairs -o  KI15cFSYM428 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15cFSYM428
iu-merge-pairs -o  KI15cFSYM432 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15cFSYM432
iu-merge-pairs -o  KI15cFSYM434 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15cFSYM434
iu-merge-pairs -o  KI15cFSYM435 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15cFSYM435
iu-merge-pairs -o  KI15cFSYM436 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15cFSYM436
iu-merge-pairs -o  KI15cFSYM439 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15cFSYM439
iu-merge-pairs -o  KI15cFSYM448 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15cFSYM448
iu-merge-pairs -o  KI15cFSYM455 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15cFSYM455
iu-merge-pairs -o  KI15cFSYM460 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15cFSYM460
iu-merge-pairs -o  KI15cFSYM461 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15cFSYM461
iu-merge-pairs -o  KI15cFSYM468 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15cFSYM468
iu-merge-pairs -o  KI15cFSYM472 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15cFSYM472
iu-merge-pairs -o  KI15cFSYM474 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15cFSYM474
iu-merge-pairs -o  KI15cFSYM488 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15cFSYM488
iu-merge-pairs -o  KI15cFSYM493 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15cFSYM493
iu-merge-pairs -o  KI15cFSYM494 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15cFSYM494
iu-merge-pairs -o  KI15cFSYM496 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15cFSYM496
iu-merge-pairs -o  KI15cFSYM499 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15cFSYM499
iu-merge-pairs -o  KI15cFSYM502 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15cFSYM502
iu-merge-pairs -o  KI15cFSYM503 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15cFSYM503
iu-merge-pairs -o  KI15cFSYM504 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15cFSYM504
iu-merge-pairs -o  KI15cFSYM506 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15cFSYM506
iu-merge-pairs -o  KI15cFSYM507 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15cFSYM507
iu-merge-pairs -o  KI15cFSYM509 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15cFSYM509
iu-merge-pairs -o  KI15cFSYM519 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15cFSYM519
iu-merge-pairs -o  KI15cSSYM001 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15cSSYM001
iu-merge-pairs -o  KI15cSSYM003 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15cSSYM003
iu-merge-pairs -o  KI15cSSYM006 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15cSSYM006
iu-merge-pairs -o  KI15cSSYM026 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15cSSYM026
iu-merge-pairs -o  KI15cSSYM028 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15cSSYM028
iu-merge-pairs -o  KI15cSSYM029 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15cSSYM029
iu-merge-pairs -o  KI15cSSYM033 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15cSSYM033
iu-merge-pairs -o  KI15cSSYM034 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15cSSYM034
iu-merge-pairs -o  KI15cSSYM036 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15cSSYM036
iu-merge-pairs -o  KI15cWSYM001 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15cWSYM001
iu-merge-pairs -o  KI15cWSYM002 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15cWSYM002
iu-merge-pairs -o  KI15cWSYM003 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15cWSYM003
iu-merge-pairs -o  KI15cWSYM004 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15cWSYM004
iu-merge-pairs -o  KI15cWSYM009 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15cWSYM009
iu-merge-pairs -o  KI15cWSYM010 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15cWSYM010
iu-merge-pairs -o  KI15cWSYM011 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15cWSYM011
iu-merge-pairs -o  KI15cWSYM012 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15cWSYM012
iu-merge-pairs -o  KI15cWSYM025 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15cWSYM025
iu-merge-pairs -o  KI15cWSYM026 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15cWSYM026
iu-merge-pairs -o  KI15cWSYM027 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15cWSYM027
iu-merge-pairs -o  KI15cWSYM028 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15cWSYM028
iu-merge-pairs -o  KI15cWSYM029 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15cWSYM029
iu-merge-pairs -o  KI15cWSYM030 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15cWSYM030
iu-merge-pairs -o  KI15cWSYM031 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15cWSYM031
iu-merge-pairs -o  KI15cWSYM032 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15cWSYM032
iu-merge-pairs -o  KI15cWSYM033 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15cWSYM033
iu-merge-pairs -o  KI15cWSYM034 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15cWSYM034
iu-merge-pairs -o  KI15cWSYM035 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15cWSYM035
iu-merge-pairs -o  KI15cWSYM036 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15cWSYM036
iu-merge-pairs -o  KI15cWSYM037 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15cWSYM037
iu-merge-pairs -o  KI15cWSYM038 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15cWSYM038
iu-merge-pairs -o  KI15cWSYM039 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15cWSYM039
iu-merge-pairs -o  KI15cWSYM040 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI15cWSYM040
iu-merge-pairs -o  KI16aFSYM001 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI16aFSYM001
iu-merge-pairs -o  KI16aFSYM004 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI16aFSYM004
iu-merge-pairs -o  KI16aFSYM006 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI16aFSYM006
iu-merge-pairs -o  KI16aFSYM009 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI16aFSYM009
iu-merge-pairs -o  KI16aFSYM010 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI16aFSYM010
iu-merge-pairs -o  KI16aFSYM011 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI16aFSYM011
iu-merge-pairs -o  KI16aFSYM013 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI16aFSYM013
iu-merge-pairs -o  KI16aFSYM017 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI16aFSYM017
iu-merge-pairs -o  KI16aFSYM018 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI16aFSYM018
iu-merge-pairs -o  KI16aFSYM020 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI16aFSYM020
iu-merge-pairs -o  KI16aFSYM021 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI16aFSYM021
iu-merge-pairs -o  KI16aFSYM024 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI16aFSYM024
iu-merge-pairs -o  KI16aFSYM027 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI16aFSYM027
iu-merge-pairs -o  KI16aFSYM029 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI16aFSYM029
iu-merge-pairs -o  KI16aFSYM033 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI16aFSYM033
iu-merge-pairs -o  KI16aFSYM035 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI16aFSYM035
iu-merge-pairs -o  KI16aFSYM038 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI16aFSYM038
iu-merge-pairs -o  KI16aFSYM039 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI16aFSYM039
iu-merge-pairs -o  KI16aFSYM040 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI16aFSYM040
iu-merge-pairs -o  KI16aFSYM043 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI16aFSYM043
iu-merge-pairs -o  KI16aFSYM044 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI16aFSYM044
iu-merge-pairs -o  KI16aFSYM047 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI16aFSYM047
iu-merge-pairs -o  KI16aFSYM048 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI16aFSYM048
iu-merge-pairs -o  KI16aFSYM049 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI16aFSYM049
iu-merge-pairs -o  KI16aFSYM054 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI16aFSYM054
iu-merge-pairs -o  KI16aFSYM056 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI16aFSYM056
iu-merge-pairs -o  KI16aFSYM057 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI16aFSYM057
iu-merge-pairs -o  KI16aFSYM058 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI16aFSYM058
iu-merge-pairs -o  KI16aFSYM059 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI16aFSYM059
iu-merge-pairs -o  KI16aFSYM062 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI16aFSYM062
iu-merge-pairs -o  KI16aFSYM066 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI16aFSYM066
iu-merge-pairs -o  KI16aFSYM069 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI16aFSYM069
iu-merge-pairs -o  KI16aFSYM070 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI16aFSYM070
iu-merge-pairs -o  KI16aFSYM072 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI16aFSYM072
iu-merge-pairs -o  KI16aFSYM073 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI16aFSYM073
iu-merge-pairs -o  KI16aFSYM074 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI16aFSYM074
iu-merge-pairs -o  KI16aFSYM076 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI16aFSYM076
iu-merge-pairs -o  KI16aFSYM077 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI16aFSYM077
iu-merge-pairs -o  KI16aFSYM080 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI16aFSYM080
iu-merge-pairs -o  KI16aFSYM082 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI16aFSYM082
iu-merge-pairs -o  KI16aFSYM083 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI16aFSYM083
iu-merge-pairs -o  KI16aFSYM086 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI16aFSYM086
iu-merge-pairs -o  KI16aFSYM087 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI16aFSYM087
iu-merge-pairs -o  KI16aFSYM088 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI16aFSYM088
iu-merge-pairs -o  KI16aFSYM089 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI16aFSYM089
iu-merge-pairs -o  KI16aFSYM091 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI16aFSYM091
iu-merge-pairs -o  KI16aFSYM094 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI16aFSYM094
iu-merge-pairs -o  KI16aFSYM095 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI16aFSYM095
iu-merge-pairs -o  KI16aFSYM096 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI16aFSYM096
iu-merge-pairs -o  KI16aFSYM101 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI16aFSYM101
iu-merge-pairs -o  KI16aFSYM104 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI16aFSYM104
iu-merge-pairs -o  KI16aFSYM107 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI16aFSYM107
iu-merge-pairs -o  KI16aFSYM108 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI16aFSYM108
iu-merge-pairs -o  KI16aFSYM113 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI16aFSYM113
iu-merge-pairs -o  KI16aFSYM116 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI16aFSYM116
iu-merge-pairs -o  KI16aFSYM118 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI16aFSYM118
iu-merge-pairs -o  KI16aFSYM119 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI16aFSYM119
iu-merge-pairs -o  KI16aFSYM120 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI16aFSYM120
iu-merge-pairs -o  KI16aFSYM121 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI16aFSYM121
iu-merge-pairs -o  KI16aFSYM123 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI16aFSYM123
iu-merge-pairs -o  KI16aFSYM151 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI16aFSYM151
iu-merge-pairs -o  KI16aFSYM153 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI16aFSYM153
iu-merge-pairs -o  KI16aFSYM155 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI16aFSYM155
iu-merge-pairs -o  KI16aFSYM158 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI16aFSYM158
iu-merge-pairs -o  KI16aFSYM159 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI16aFSYM159
iu-merge-pairs -o  KI16aFSYM160 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI16aFSYM160
iu-merge-pairs -o  KI16aFSYM164 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI16aFSYM164
iu-merge-pairs -o  KI16aFSYM190 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI16aFSYM190
iu-merge-pairs -o  KI16aFSYM196 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI16aFSYM196
iu-merge-pairs -o  KI16aFSYM212 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI16aFSYM212
iu-merge-pairs -o  KI16aFSYM214 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI16aFSYM214
iu-merge-pairs -o  KI16aFSYM215 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI16aFSYM215
iu-merge-pairs -o  KI16aFSYM217 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI16aFSYM217
iu-merge-pairs -o  KI16aFSYM220 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI16aFSYM220
iu-merge-pairs -o  KI16aFSYM221 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI16aFSYM221
iu-merge-pairs -o  KI16aFSYM223 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI16aFSYM223
iu-merge-pairs -o  KI16aFSYM225 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI16aFSYM225
iu-merge-pairs -o  KI16aFSYM226 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI16aFSYM226
iu-merge-pairs -o  KI16aFSYM229 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI16aFSYM229
iu-merge-pairs -o  KI16aFSYM231 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI16aFSYM231
iu-merge-pairs -o  KI16aFSYM233 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI16aFSYM233
iu-merge-pairs -o  KI16aFSYM235 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI16aFSYM235
iu-merge-pairs -o  KI16aFSYM237 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI16aFSYM237
iu-merge-pairs -o  KI16aFSYM238 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI16aFSYM238
iu-merge-pairs -o  KI16aFSYM239 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI16aFSYM239
iu-merge-pairs -o  KI16aFSYM256 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI16aFSYM256
iu-merge-pairs -o  KI16aFSYM259 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI16aFSYM259
iu-merge-pairs -o  KI16aFSYM260 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI16aFSYM260
iu-merge-pairs -o  KI16aFSYM261 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI16aFSYM261
iu-merge-pairs -o  KI16aFSYM262 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI16aFSYM262
iu-merge-pairs -o  KI16aFSYM264 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI16aFSYM264
iu-merge-pairs -o  KI16aFSYM265 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI16aFSYM265
iu-merge-pairs -o  KI16aFSYM266 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI16aFSYM266
iu-merge-pairs -o  KI16aFSYM268 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI16aFSYM268
iu-merge-pairs -o  KI16aFSYM272 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI16aFSYM272
iu-merge-pairs -o  KI16aFSYM273 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI16aFSYM273
iu-merge-pairs -o  KI16aFSYM274 --enforce-Q30-check /Users/danielle/Documents/Data_Analysis/KI_Platy/analyses/configs/merge_config_KI16aFSYM274