---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(phyloseq)
library(ggplot2)
library(caret)
library(plyr)
library(dplyr)

# Load grouped data
load("C:/Users/Dani/Documents/Data_Analysis/KI_Platy/data/otus_97/KI_Platy_f_grouped.RData")

```

```{r, include=TRUE}
# Subset samples to only include corals
phy97.f.C <- subset_samples(phy97.f,SampleType == "coral")
pslog <- transform_sample_counts(phy97.f.C, function(x) log(1 + x))
sample_data(pslog)$SampleID <- rownames(sample_data(pslog)) %>%
  as.factor()

sample_data(pslog)$Year <- as.numeric(sample_data(pslog)$Year)
sample_data(pslog)$Year2 <- cut(sample_data(pslog)$Year, c(0,1,2,3,4,5))
dataMatrix <- data.frame(Year = sample_data(pslog)$Year2, sample_data(pslog))
dataMatrix <- dataMatrix[c(3,7:9,12)]

trainingCorals <- sample(unique(sample_data(pslog)$SampleID), size = 200)
inTrain <- which(sample_data(pslog)$SampleID %in% trainingCorals)
training <- dataMatrix[inTrain,]
testing <- dataMatrix[-inTrain,]
plsFit <- train(Year2 ~ ., data = training,
		  method = "pls", preProc = "center")
plsClasses <- predict(plsFit, newdata = testing)
table(plsClasses, testing$Year2)

sample_data(pslog)$Year <- as.numeric(sample_data(pslog)$Year)
sample_data(pslog)$Year2 <- cut(sample_data(pslog)$Year, c(0,2,3,5))
dataMatrix <- data.frame(Year = sample_data(pslog)$Year2, sample_data(pslog))
dataMatrix <- dataMatrix[c(3,7:9,12)]

trainingCorals <- sample(unique(sample_data(pslog)$SampleID), size = 200)
inTrain <- which(sample_data(pslog)$SampleID %in% trainingCorals)
training <- dataMatrix[inTrain,]
testing <- dataMatrix[-inTrain,]
plsFit <- train(Year2 ~ ., data = training,
		  method = "pls", preProc = "center")
plsClasses <- predict(plsFit, newdata = testing)
table(plsClasses, testing$Year2)

rfFit <- train(Year2 ~ Coral_Species, data = training, method = "rf",
 		 preProc = "center", proximity = TRUE)
rfClasses <- predict(rfFit, newdata = testing)
table(rfClasses, testing$Year2)

```