---
title: "KI_Platy_Ordination"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

rm(list=ls())

library(phyloseq)
library(vegan)
library(ggplot2)
library(phangorn)

load("C:/Users/Dani/Documents/Data_Analysis/KI_Platy/data/KI_seqs_f_coral_grouped.RData")

```
## Ordinate *Symbiodinium* communities
```{r echo=FALSE}
# Do an unconstrained ordination on all coral data, using weighted unifrac distances
ord.phy97.f.c.coral.AD <- ordinate(phy97.f.c.coral.AD,method="PCoA",distance="wunifrac")
# Plot this ordination (this has lots of data, so it takes a while to run)
plot_ordination(phy97.f.c.coral.AD, ord.phy97.f.c.coral.AD,  color="Coral_Species", shape="Status",title="97% within-sample OTUs - PCoA") 

# Do an unconstrained ordination on all coral data before the event, using weighted unifrac distances
ord.phy97.f.c.coral.AD.before <- ordinate(phy97.f.c.coral.AD.before,method="PCoA",distance="wunifrac")
# Plot this ordination 
plot_ordination(phy97.f.c.coral.AD.before, ord.phy97.f.c.coral.AD.before,  color="Status", shape="Coral_Species", title="97% within-sample OTUs - PCoA") 

# Do an unconstrained ordination on only Platygyra corals, using weighted unifrac distances
ord.phy97.f.c.platy.AD <- ordinate(phy97.f.c.platy.AD,method="PCoA",distance="wunifrac")
# Plot this ordination 
plot_ordination(phy97.f.c.platy.AD, ord.phy97.f.c.platy.AD, color="Status", shape="Year",
                title="97% within-sample OTUs - PCoA - Platy only")

# Do an unconstrained ordination on only Platygyra corals before the event, using weighted unifrac distances
ord.phy97.f.c.platy.AD.before <- ordinate(phy97.f.c.platy.AD.before,method="PCoA",distance="wunifrac")
# Plot this ordination 
plot_ordination(phy97.f.c.platy.AD.before, ord.phy97.f.c.platy.AD.before, color="Dist", 
                shape="Year",title="97% within-sample OTUs - PCoA - Platy only")

# Do a constrained ordination on Platygyra corals
ord.phy97.f.c.platy.AD.CAP <- ordinate(phy97.f.c.platy.AD,method="CAP",distance="wunifrac",formula= ~ Year + Dist + Status)
# Plot this ordination - scree plot
plot_ordination(phy97.f.c.platy.AD, ord.phy97.f.c.platy.AD.CAP,  shape="Status",type="scree",
                title="97% within-sample OTUs - CAP Platygyra only")
# Plot this ordination - sample plot
plot_ordination(phy97.f.c.platy.AD, ord.phy97.f.c.platy.AD.CAP,  shape="Status", color="Dist",type="samples",title="97% within-sample OTUs - CAP Platygyra only")
# Test ordination
anova(ord.phy97.f.c.platy.AD.CAP)
# Use ordistep to assess which model terms should be included
finalmodel.platy.AD <- ordistep(ord.phy97.f.c.platy.AD.CAP, formula= ~ Year + Dist + Status, direction = c("both"), Pin = 0.05, Pout = 0.1, pstep = 100, perm.max = 1000, steps = 50, trace = TRUE)
# Look at the ordistep final model
finalmodel.platy.AD
# Check for covariance
vif.cca(finalmodel.platy.AD)
# Test the full model
anova.cca(finalmodel.platy.AD)
# Test the model terms
anova.cca(finalmodel.platy.AD, by="terms")

# Do a constrained ordination on Platygyra corals before the event
ord.phy97.f.c.platy.AD.before.CAP <- ordinate(phy97.f.c.platy.AD.before,method="CAP",distance="wunifrac",formula= ~ Year + Status + Dist)
# Plot this ordination - scree plot
plot_ordination(phy97.f.c.platy.AD.before, ord.phy97.f.c.platy.AD.before.CAP,  shape="Status",type="scree",
                title="97% within-sample OTUs - CAP Platygyra only")
# Plot this ordination - sample plot
plot_ordination(phy97.f.c.platy.AD.before, ord.phy97.f.c.platy.AD.before.CAP,  shape="Status", color="Site",type="samples",title="97% within-sample OTUs - CAP Platygyra only")
# Test ordination
anova(ord.phy97.f.c.platy.AD.before.CAP)
# Use ordistep to assess which model terms should be included
finalmodel.platy.AD.before <- ordistep(ord.phy97.f.c.platy.AD.before.CAP, formula= ~ Year + Status +  Dist, direction = c("both"), Pin = 0.05, Pout = 0.1, pstep = 100, perm.max = 1000, steps = 50, trace = TRUE)
# Look at the ordistep final model
finalmodel.platy.AD.before
# Check for covariance
vif.cca(finalmodel.platy.AD.before)
# Test the full model
anova.cca(finalmodel.platy.AD.before)
# Test the model terms
anova.cca(finalmodel.platy.AD.before, by="terms")

# Do a constrained ordination on all corals
ord.phy97.f.c.coral.AD.CAP <- ordinate(phy97.f.c.coral.AD,method="CAP",distance="wunifrac",formula= ~ Year + Status + Dist + Coral_Species + Year*Status + Year*Dist + Year*Coral_Species + Status*Dist + Status*Coral_Species + Dist*Coral_Species)
# Plot this ordination - scree plot
plot_ordination(phy97.f.c.coral.AD, ord.phy97.f.c.coral.AD.CAP,  shape="Status",type="scree",
                title="97% within-sample OTUs - CAP all corals")
# Plot this ordination - sample plot
plot_ordination(phy97.f.c.coral.AD, ord.phy97.f.c.coral.AD.CAP,  shape="Status", color="Site",type="samples",title="97% within-sample OTUs - CAP all corals")
# Test ordination
anova(ord.phy97.f.c.coral.AD.CAP)
# Use ordistep to assess which model terms should be included
finalmodel.coral.AD <- ordistep(ord.phy97.f.c.coral.AD.CAP, formula= ~ Year + Status + Dist + Coral_Species + Year*Status + Year*Dist + Year*Coral_Species + Status*Dist + Status*Coral_Species + Dist*Coral_Species, direction = c("both"), Pin = 0.05, Pout = 0.1, pstep = 100, perm.max = 1000, steps = 50, trace = TRUE)
# Look at the ordistep final model
finalmodel.coral.AD
# Check for covariance
vif.cca(finalmodel.coral.AD)
# Test the full model
anova.cca(finalmodel.coral.AD)
# Test the model terms
anova.cca(finalmodel.coral.AD, by="terms")

# Do a constrained ordination on fpenta corals before the event
ord.phy97.f.c.fpenta.AD.before.CAP <- ordinate(phy97.f.c.fpenta.AD.before,method="CAP",distance="wunifrac",formula= ~ Year + Status + Dist)
# Plot this ordination - scree plot
plot_ordination(phy97.f.c.fpenta.AD.before, ord.phy97.f.c.fpenta.AD.before.CAP,  shape="Status",type="scree",
                title="97% within-sample OTUs - CAP fpenta only")
# Plot this ordination - sample plot
plot_ordination(phy97.f.c.fpenta.AD.before, ord.phy97.f.c.fpenta.AD.before.CAP, shape="Status", color="Dist",type="samples",title="97% within-sample OTUs - CAP fpenta only")
# Test ordination
anova(ord.phy97.f.c.fpenta.AD.before.CAP)
# Use ordistep to assess which model terms should be included
finalmodel.fpenta.AD.before <- ordistep(ord.phy97.f.c.fpenta.AD.before.CAP, formula= ~ Year + Status +  Dist, direction = c("both"), Pin = 0.05, Pout = 0.1, pstep = 100, perm.max = 1000, steps = 50, trace = TRUE)
# Look at the ordistep final model
finalmodel.fpenta.AD.before
# Check for covariance
vif.cca(finalmodel.fpenta.AD.before)
# Test the full model
anova.cca(finalmodel.fpenta.AD.before)
# Test the model terms
anova.cca(finalmodel.fpenta.AD.before, by="terms")

ord.phy97.f.c.fpenta.AD.CAP <- ordinate(phy97.f.c.fpenta.AD,method="CAP",distance="wunifrac",formula= ~ Year + Dist + Status)
# Plot this ordination - sample plot
plot_ordination(phy97.f.c.fpenta.AD, ord.phy97.f.c.fpenta.AD.CAP,  shape="Status", color="Dist",type="samples",title="97% within-sample OTUs - CAP Fpenta only")


# Do a constrained ordination on fpenta and platygyra corals together before the event
ord.phy97.f.c.platyfpenta.AD.before.CAP <- ordinate(phy97.f.c.coral.now.AD.before,method="CAP",distance="wunifrac",formula= ~ Year + Status + Dist + Coral_Species)
# Plot this ordination - scree plot
plot_ordination(phy97.f.c.coral.now.AD.before, ord.phy97.f.c.platyfpenta.AD.before.CAP,  shape="Status",type="scree", title="97% within-sample OTUs - CAP Fpenta and Platy")
# Plot this ordination - sample plot
plot_ordination(phy97.f.c.coral.now.AD.before, ord.phy97.f.c.platyfpenta.AD.before.CAP, shape="Status", color="Dist",type="samples",title="97% within-sample OTUs - CAP FPenta and Platy only before bleaching")
# Test ordination
anova(ord.phy97.f.c.platyfpenta.AD.before.CAP)
# Use ordistep to assess which model terms should be included
finalmodel.platyfpenta.AD.before <- ordistep(ord.phy97.f.c.platyfpenta.AD.before.CAP, formula= ~ Year + Status +  Dist + Coral_Species, direction = c("both"), Pin = 0.05, Pout = 0.1, pstep = 100, perm.max = 1000, steps = 50, trace = TRUE)
# Look at the ordistep final model
finalmodel.platyfpenta.AD.before
# Check for covariance
vif.cca(finalmodel.platyfpenta.AD.before)
# Test the full model
anova.cca(finalmodel.platyfpenta.AD.before)
# Test the model terms
anova.cca(finalmodel.platyfpenta.AD.before, by="terms")

# Do a constrained ordination on fpenta and platygyra corals together before the event
ord.phy97.f.c.platyfpenta.AD.CAP <- ordinate(phy97.f.c.coral.now.AD,method="CAP",distance="wunifrac",formula= ~ Year + Status + Dist + Coral_Species)
# Plot this ordination - scree plot
plot_ordination(phy97.f.c.coral.now.AD, ord.phy97.f.c.platyfpenta.AD.CAP,  shape="Status",type="scree", title="97% within-sample OTUs - CAP Fpenta and Platy")
# Plot this ordination - sample plot
plot_ordination(phy97.f.c.coral.now.AD, ord.phy97.f.c.platyfpenta.AD.CAP, shape="Status", color="Dist",type="samples",title="97% within-sample OTUs - CAP FPenta and Platy only all samples")
# Test ordination
anova(ord.phy97.f.c.platyfpenta.AD.CAP)
# Use ordistep to assess which model terms should be included
finalmodel.platyfpenta.AD <- ordistep(ord.phy97.f.c.platyfpenta.AD.CAP, formula= ~ Year + Status +  Dist + Coral_Species, direction = c("both"), Pin = 0.05, Pout = 0.1, pstep = 100, perm.max = 1000, steps = 50, trace = TRUE)
# Look at the ordistep final model
finalmodel.platyfpenta.AD
# Check for covariance
vif.cca(finalmodel.platyfpenta.AD)
# Test the full model
anova.cca(finalmodel.platyfpenta.AD)
# Test the model terms
anova.cca(finalmodel.platyfpenta.AD, by="terms")

```

```{r sat_curves}
coralsat <- specaccum(otu_table(phy97.f.c.coral), method = "exact", permutations = 100)
plot(coralsat)
platysat <- specaccum(otu_table(phy97.f.c.platy), method = "coleman", permutations = 100)
plot(platysat)
```

```{r richness_plot}
plot_richness(phy97.f.c.platy.AD, x="Status",color="Year", measures=c("Observed", "Shannon"))
phy97.f.c.platy.AD.Year = merge_samples(phy97.f.c.platy.AD, "Year")
# repair variables that were damaged during merge (coerced to numeric)
sample_data(phy97.f.c.platy.AD.Year)$Year <- factor(sample_names(phy97.f.c.platy.AD.Year), levels=c("2014","2015Jan","2015May","2015July","2016March"))

p = plot_richness(phy97.f.c.platy.AD.Year, x="Year", color="Year", measures=c("Observed", "Shannon"))
p + geom_point(size=5, alpha=0.7)

phy97.f.c.platy.AD.Status = merge_samples(phy97.f.c.platy.AD, "Status")
# repair variables that were damaged during merge (coerced to numeric)
sample_data(phy97.f.c.platy.AD.Status)$Status <- factor(sample_names(phy97.f.c.platy.AD.Status), levels=c("alive","dead"))

p = plot_richness(phy97.f.c.platy.AD.Status, x="Status", color="Status", measures=c("Observed", "Shannon"))
p + geom_point(size=5, alpha=0.7)

phy97.f.c.platy.AD.before.Status = merge_samples(phy97.f.c.platy.AD.before, "Status")
# repair variables that were damaged during merge (coerced to numeric)
sample_data(phy97.f.c.platy.AD.before.Status)$Status <- factor(sample_names(phy97.f.c.platy.AD.before.Status), levels=c("alive","dead"))

p = plot_richness(phy97.f.c.platy.AD.before.Status, x="Status", color="Status", measures=c("Observed","Shannon"))
p + geom_point(size=5, alpha=0.7)


phy97.f.c.fpenta.AD.Status = merge_samples(phy97.f.c.fpenta.AD, "Status")
# repair variables that were damaged during merge (coerced to numeric)
sample_data(phy97.f.c.fpenta.AD.Status)$Status <- factor(sample_names(phy97.f.c.fpenta.AD.Status), levels=c("alive","dead"))

p = plot_richness(phy97.f.c.fpenta.AD.Status, x="Status", color="Status", measures=c("Observed", "Shannon"))
p + geom_point(size=5, alpha=0.7)
```

```{r upgma_comm_trees, include=FALSE}
dist.phy97.f.c.coral <- distance(phy97.f.c.coral, method="unifrac", type="samples")
upgma.phy97.f.c.coral <-  upgma(dist.phy97.f.c.coral)
plot(upgma.phy97.f.c.coral)

cols= c("red","orange","green","turquoise","blue")

sample_data(phy97.f.c.platy.AD.before)$Dist <- factor(sample_data(phy97.f.c.platy.AD.before)$Dist,levels=c("VeryHigh","High","HighMed","Low","VeryLow"))

par(mar=c(0,0,0,0))
dist.phy97.f.c.platy.AD.before <- distance(phy97.f.c.platy.AD.before, method="unifrac", type="samples")
upgma.phy97.f.c.platy.AD.before <-  upgma(dist.phy97.f.c.platy.AD.before)
plot(upgma.phy97.f.c.platy.AD.before,show.tip.label = TRUE, tip.color = "white")
phy97.f.c.platy.AD.before.tip.labels <- get_variable(phy97.f.c.platy.AD.before, "Status")
tiplabels(phy97.f.c.platy.AD.before.tip.labels, col = c(phy97.f.c.platy.AD.before.tip.labels), frame = "none", adj = -0.05, cex = 0.7)
```
