---
title: "Platy analysis - Phyloseq Cleanup"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<!-- Import libraries -->
```{r, echo=FALSE}
library(stringr)
library(reshape2)
library(phyloseq)
```

<!-- Load filtered RData object from output of filter_notsym.R script -->
```{r, echo=FALSE}
load("C:/Users/Dani/Documents/Data_Analysis/KI_Platy/data/otus_97/KI_Platy_f.RData")
phy97.f <- phy.f # Rename phyloseq object for clarity
```


<!-- Characterize sites by disturbance level -->
```{r, echo=FALSE}
VeryHigh <- c(33,40,32,31,27,30,26)
High <- c(25,3,38,24)
HighMed <- c(9,34,35,8,14,6)
LowMed <- c(2,22,1,23)
Low <- c(7,13,12,4,36,5,37)
VeryLow <- c(10,21,11,20,16,15,39,19,18,17)

sample_data(phy97.f)$Site <- factor(sample_data(phy97.f)$Site)
sample_data(phy97.f)$Dist <- sample_data(phy97.f)$Site
sample_data(phy97.f)$Dist<- gsub ("34",as.character("HighMed"), as.character(data.frame(sample_data(phy97.f))$Dist), as.character("HighMed"))
sample_data(phy97.f)$Dist<- gsub ("35",as.character("HighMed"), as.character(data.frame(sample_data(phy97.f))$Dist), as.character("HighMed"))
sample_data(phy97.f)$Dist<- gsub ("14",as.character("HighMed"), as.character(data.frame(sample_data(phy97.f))$Dist), as.character("HighMed"))
sample_data(phy97.f)$Dist<- gsub ("15",as.character("VeryLow"), as.character(data.frame(sample_data(phy97.f))$Dist), as.character("HighMed"))
sample_data(phy97.f)$Dist<- gsub ("19",as.character("VeryLow"), as.character(data.frame(sample_data(phy97.f))$Dist), as.character("HighMed"))
sample_data(phy97.f)$Dist<- gsub ("12",as.character("Low"), as.character(data.frame(sample_data(phy97.f))$Dist), as.character("HighMed"))
sample_data(phy97.f)$Dist<- gsub ("37",as.character("Low"), as.character(data.frame(sample_data(phy97.f))$Dist), as.character("HighMed"))
sample_data(phy97.f)$Dist<- gsub ("27",as.character("VeryHigh"), as.character(data.frame(sample_data(phy97.f))$Dist), as.character("HighMed"))
sample_data(phy97.f)$Dist<- gsub ("30",as.character("VeryHigh"), as.character(data.frame(sample_data(phy97.f))$Dist), as.character("HighMed"))
sample_data(phy97.f)$Dist<- gsub ("32",as.character("VeryHigh"), as.character(data.frame(sample_data(phy97.f))$Dist), as.character("HighMed"))
sample_data(phy97.f)$Dist<- gsub ("26",as.character("VeryHigh"), as.character(data.frame(sample_data(phy97.f))$Dist), as.character("HighMed"))
sample_data(phy97.f)$Dist<- gsub ("31",as.character("VeryHigh"), as.character(data.frame(sample_data(phy97.f))$Dist), as.character("HighMed"))
sample_data(phy97.f)$Dist<- gsub ("40",as.character("VeryHigh"), as.character(data.frame(sample_data(phy97.f))$Dist), as.character("HighMed"))
sample_data(phy97.f)$Dist<- gsub ("33",as.character("VeryHigh"), as.character(data.frame(sample_data(phy97.f))$Dist), as.character("HighMed"))
sample_data(phy97.f)$Dist<- gsub ("38",as.character("VeryHigh"), as.character(data.frame(sample_data(phy97.f))$Dist), as.character("High"))
sample_data(phy97.f)$Dist<- gsub ("25",as.character("VeryHigh"), as.character(data.frame(sample_data(phy97.f))$Dist), as.character("High"))
sample_data(phy97.f)$Dist<- gsub ("24",as.character("VeryHigh"), as.character(data.frame(sample_data(phy97.f))$Dist), as.character("High"))
sample_data(phy97.f)$Dist<- gsub ("3",as.character("VeryHigh"), as.character(data.frame(sample_data(phy97.f))$Dist), as.character("High"))
sample_data(phy97.f)$Dist<- gsub ("5",as.character("Low"), as.character(data.frame(sample_data(phy97.f))$Dist), as.character("HighMed"))
sample_data(phy97.f)$Dist<- gsub ("6",as.character("HighMed"), as.character(data.frame(sample_data(phy97.f))$Dist), as.character("HighMed"))
sample_data(phy97.f)$Dist<- gsub ("9",as.character("HighMed"), as.character(data.frame(sample_data(phy97.f))$Dist), as.character("HighMed"))
sample_data(phy97.f)$Dist<- gsub ("8",as.character("HighMed"), as.character(data.frame(sample_data(phy97.f))$Dist), as.character("HighMed"))
```

<!-- Use merge_taxa to collapse OTUs with equivalent names ("hits") -->
```{r, echo=FALSE}
#phy97.f.test <- tax_glom(phy97.f, taxrank=rank_names(phy97.f)[9])
#tax_glom(physeq=myData, taxrank=rank_names(myData)[2])
#identical(tax_table(phy97.f),tax_table(phy97.f.test))

# Ok fine I'll do it the long way around
C3k_AY589737 <- grep("C3k_AY589737", data.frame(tax_table(phy97.f))$hit)
phy97.f.c <- merge_taxa(phy97.f, eqtaxa=C3k_AY589737, archetype=1)
tt <- data.frame(tax_table(phy97.f.c), stringsAsFactors = F)
isna <- rownames(tt)[is.na(tt$hit)]
info <- data.frame(tax_table(phy97.f), stringsAsFactors = F)[isna, "hit"]
tt[isna,"hit"] <- info
tax_table(phy97.f.c) <- as.matrix(tt)

D1_multiple <- grep("D1_multiple", data.frame(tax_table(phy97.f.c))$hit)
phy97.f.c <- merge_taxa(phy97.f.c, eqtaxa=D1_multiple, archetype=1)
tt <- data.frame(tax_table(phy97.f.c), stringsAsFactors = F)
isna <- rownames(tt)[is.na(tt$hit)]
info <- data.frame(tax_table(phy97.f), stringsAsFactors = F)[isna, "hit"]
tt[isna,"hit"] <- info
tax_table(phy97.f.c) <- as.matrix(tt)

C42_AY258487 <- grep("C42_AY258487", data.frame(tax_table(phy97.f.c))$hit)
phy97.f.c <- merge_taxa(phy97.f.c, eqtaxa=C42_AY258487, archetype=1)
tt <- data.frame(tax_table(phy97.f.c), stringsAsFactors = F)
isna <- rownames(tt)[is.na(tt$hit)]
info <- data.frame(tax_table(phy97.f), stringsAsFactors = F)[isna, "hit"]
tt[isna,"hit"] <- info
tax_table(phy97.f.c) <- as.matrix(tt)

C15_AY239369 <- grep("C15_AY239369", data.frame(tax_table(phy97.f.c))$hit)
phy97.f.c <- merge_taxa(phy97.f.c, eqtaxa=C15_AY239369, archetype=1)
tt <- data.frame(tax_table(phy97.f.c), stringsAsFactors = F)
isna <- rownames(tt)[is.na(tt$hit)]
info <- data.frame(tax_table(phy97.f), stringsAsFactors = F)[isna, "hit"]
tt[isna,"hit"] <- info
tax_table(phy97.f.c) <- as.matrix(tt)

C3_multiple <- grep("C3_multiple", data.frame(tax_table(phy97.f.c))$hit)
phy97.f.c <- merge_taxa(phy97.f.c, eqtaxa=C3_multiple, archetype=1)
tt <- data.frame(tax_table(phy97.f.c), stringsAsFactors = F)
isna <- rownames(tt)[is.na(tt$hit)]
info <- data.frame(tax_table(phy97.f), stringsAsFactors = F)[isna, "hit"]
tt[isna,"hit"] <- info
tax_table(phy97.f.c) <- as.matrix(tt)

I4_FN561562 <- grep("I4_FN561562", data.frame(tax_table(phy97.f.c))$hit)
phy97.f.c <- merge_taxa(phy97.f.c, eqtaxa=I4_FN561562, archetype=1)
tt <- data.frame(tax_table(phy97.f.c), stringsAsFactors = F)
isna <- rownames(tt)[is.na(tt$hit)]
info <- data.frame(tax_table(phy97.f), stringsAsFactors = F)[isna, "hit"]
tt[isna,"hit"] <- info
tax_table(phy97.f.c) <- as.matrix(tt)

G100_AB253788 <- grep("G100_AB253788", data.frame(tax_table(phy97.f.c))$hit)
phy97.f.c <- merge_taxa(phy97.f.c, eqtaxa=G100_AB253788, archetype=1)
tt <- data.frame(tax_table(phy97.f.c), stringsAsFactors = F)
isna <- rownames(tt)[is.na(tt$hit)]
info <- data.frame(tax_table(phy97.f), stringsAsFactors = F)[isna, "hit"]
tt[isna,"hit"] <- info
tax_table(phy97.f.c) <- as.matrix(tt)

F5.2c_AM748596 <- grep("F5.2c_AM748596", data.frame(tax_table(phy97.f.c))$hit)
phy97.f.c <- merge_taxa(phy97.f.c, eqtaxa=F5.2c_AM748596, archetype=1)
tt <- data.frame(tax_table(phy97.f.c), stringsAsFactors = F)
isna <- rownames(tt)[is.na(tt$hit)]
info <- data.frame(tax_table(phy97.f), stringsAsFactors = F)[isna, "hit"]
tt[isna,"hit"] <- info
tax_table(phy97.f.c) <- as.matrix(tt)

F5.1a_AM748591 <- grep("F5.1a_AM748591", data.frame(tax_table(phy97.f.c))$hit)
phy97.f.c <- merge_taxa(phy97.f.c, eqtaxa=F5.1a_AM748591, archetype=1)
tt <- data.frame(tax_table(phy97.f.c), stringsAsFactors = F)
isna <- rownames(tt)[is.na(tt$hit)]
info <- data.frame(tax_table(phy97.f), stringsAsFactors = F)[isna, "hit"]
tt[isna,"hit"] <- info
tax_table(phy97.f.c) <- as.matrix(tt)

F3.2a_AM748568 <- grep("F3.2a_AM748568", data.frame(tax_table(phy97.f.c))$hit)
phy97.f.c <- merge_taxa(phy97.f.c, eqtaxa=F3.2a_AM748568, archetype=1)
tt <- data.frame(tax_table(phy97.f.c), stringsAsFactors = F)
isna <- rownames(tt)[is.na(tt$hit)]
info <- data.frame(tax_table(phy97.f), stringsAsFactors = F)[isna, "hit"]
tt[isna,"hit"] <- info
tax_table(phy97.f.c) <- as.matrix(tt)

C3b_AF499791 <- grep("C3b_AF499791", data.frame(tax_table(phy97.f.c))$hit)
phy97.f.c <- merge_taxa(phy97.f.c, eqtaxa=C3b_AF499791, archetype=1)
tt <- data.frame(tax_table(phy97.f.c), stringsAsFactors = F)
isna <- rownames(tt)[is.na(tt$hit)]
info <- data.frame(tax_table(phy97.f), stringsAsFactors = F)[isna, "hit"]
tt[isna,"hit"] <- info
tax_table(phy97.f.c) <- as.matrix(tt)

C1051_AF195153 <- grep("C1051_AF195153", data.frame(tax_table(phy97.f.c))$hit)
phy97.f.c <- merge_taxa(phy97.f.c, eqtaxa=C1051_AF195153, archetype=1)
tt <- data.frame(tax_table(phy97.f.c), stringsAsFactors = F)
isna <- rownames(tt)[is.na(tt$hit)]
info <- data.frame(tax_table(phy97.f), stringsAsFactors = F)[isna, "hit"]
tt[isna,"hit"] <- info
tax_table(phy97.f.c) <- as.matrix(tt)

C1232_EU118163 <- grep("C1232_EU118163", data.frame(tax_table(phy97.f.c))$hit)
phy97.f.c <- merge_taxa(phy97.f.c, eqtaxa=C1232_EU118163, archetype=1)
tt <- data.frame(tax_table(phy97.f.c), stringsAsFactors = F)
isna <- rownames(tt)[is.na(tt$hit)]
info <- data.frame(tax_table(phy97.f), stringsAsFactors = F)[isna, "hit"]
tt[isna,"hit"] <- info
tax_table(phy97.f.c) <- as.matrix(tt)

A133_DQ174725 <- grep("A133_DQ174725", data.frame(tax_table(phy97.f.c))$hit)
phy97.f.c <- merge_taxa(phy97.f.c, eqtaxa=A133_DQ174725, archetype=1)
tt <- data.frame(tax_table(phy97.f.c), stringsAsFactors = F)
isna <- rownames(tt)[is.na(tt$hit)]
info <- data.frame(tax_table(phy97.f), stringsAsFactors = F)[isna, "hit"]
tt[isna,"hit"] <- info
tax_table(phy97.f.c) <- as.matrix(tt)

# Manually checking whether all equivalent taxa are collapsed
# t <- sort(data.frame(tax_table(phy97.f.c))$hit)
# t
# 
# Check if all equivalent taxa are collapsed
# x <- length(unique(data.frame(tax_table(phy97.f.c))$hit))
# y <- length(data.frame(tax_table(phy97.f.c))$hit)
# identical(x,y)

# Transform sample counts to proportional abundance for downstream analyses
phy97.f.c.p <- transform_sample_counts(phy97.f.c, function(x) x/sum(x))
```

<!-- Use merge_taxa to collapse OTUs by clade -->
```{r, echo=FALSE}
# Find all entries in the taxa_table that contain DI in "hit"
Ds <- grep("^D", data.frame(tax_table(phy97.f))$hit)
# Merge taxa, collapsing all hits with "D1" into 1 row in the taxa table. Eqtaxa says which taxa to collapse together. Archetype is included or it doesn't work, and refers to which name the new collapsed row will take - however I haven't found out how to modify this without it failing yet.
phy97.f.clade <- merge_taxa(phy97.f, eqtaxa=Ds, archetype=1)
# Create tt from the taxa table (to use in renaming below)
tt <- data.frame(tax_table(phy97.f.clade), stringsAsFactors = F)
# Create "isna" which includes the rownames of all taxa where "hit"=NA
isna <- rownames(tt)[is.na(tt$hit)]
# Create info by extracting the row's "hit" string from the original taxa table
info <- "D"
# Rename the NA using the extracted "hit" name from above
tt[isna,"hit"] <- info
# Replace the taxa table in phy97.f.eqtaxa with updated taxa table (tt). Must be converted to matrix first to work.
tax_table(phy97.f.clade) <- as.matrix(tt)

Cs <- grep("^C", data.frame(tax_table(phy97.f.clade))$hit)
phy97.f.clade <- merge_taxa(phy97.f.clade, eqtaxa=Cs, archetype=1)
tt <- data.frame(tax_table(phy97.f.clade), stringsAsFactors = F)
isna <- rownames(tt)[is.na(tt$hit)]
info <- "C"
tt[isna,"hit"] <- info
tax_table(phy97.f.clade) <- as.matrix(tt)

Gs <- grep("^G", data.frame(tax_table(phy97.f.clade))$hit)
phy97.f.clade <- merge_taxa(phy97.f.clade, eqtaxa=Gs, archetype=1)
tt <- data.frame(tax_table(phy97.f.clade), stringsAsFactors = F)
isna <- rownames(tt)[is.na(tt$hit)]
info <- "G"
tt[isna,"hit"] <- info
tax_table(phy97.f.clade) <- as.matrix(tt)

As <- grep("^A", data.frame(tax_table(phy97.f.clade))$hit)
phy97.f.clade <- merge_taxa(phy97.f.clade, eqtaxa=As, archetype=1)
tt <- data.frame(tax_table(phy97.f.clade), stringsAsFactors = F)
isna <- rownames(tt)[is.na(tt$hit)]
info <- "A"
tt[isna,"hit"] <- info
tax_table(phy97.f.clade) <- as.matrix(tt)

Fs <- grep("^F", data.frame(tax_table(phy97.f.clade))$hit)
phy97.f.clade <- merge_taxa(phy97.f.clade, eqtaxa=Fs, archetype=1)
tt <- data.frame(tax_table(phy97.f.clade), stringsAsFactors = F)
isna <- rownames(tt)[is.na(tt$hit)]
info <- "F"
tt[isna,"hit"] <- info
tax_table(phy97.f.clade) <- as.matrix(tt)

Is <- grep("^I", data.frame(tax_table(phy97.f.clade))$hit)
phy97.f.clade <- merge_taxa(phy97.f.clade, eqtaxa=Is, archetype=1)
tt <- data.frame(tax_table(phy97.f.clade), stringsAsFactors = F)
isna <- rownames(tt)[is.na(tt$hit)]
info <- "I"
tt[isna,"hit"] <- info
tax_table(phy97.f.clade) <- as.matrix(tt)

# Transform sample counts to proportional abundance for downstream analyses
phy97.f.clade.p <- transform_sample_counts(phy97.f.clade, function(x) x/sum(x))
```

<!-- Subset into coral species -->
```{r, echo=FALSE}
# Subset coral data set into individual genus data sets
phy97.f.c.platy <- subset_samples(phy97.f.c,Coral_Species=="Platygyra_sp")
phy97.f.c.platy <- subset_taxa(phy97.f.c.platy, taxa_sums(phy97.f.c.platy) > 0, prune=TRUE)

phy97.f.c.fpenta <- subset_samples(phy97.f.c,Coral_Species=="Favites_pentagona")
phy97.f.c.fpenta <- subset_taxa(phy97.f.c.fpenta, taxa_sums(phy97.f.c.fpenta) > 0, prune=TRUE)

phy97.f.c.faviasp <- subset_samples(phy97.f.c,Coral_Species=="Favia_sp")
phy97.f.c.faviam <- subset_samples(phy97.f.c,Coral_Species=="Favia_matthai")
phy97.f.c.faviaall <- merge_phyloseq(phy97.f.c.faviasp,phy97.f.c.faviam)
phy97.f.c.faviaall <- subset_taxa(phy97.f.c.faviaall, taxa_sums(phy97.f.c.faviaall) > 0, prune=TRUE)

phy97.f.c.water <- subset_samples(phy97.f.c,Coral_Species=="water")
phy97.f.c.water <- subset_taxa(phy97.f.c.water, taxa_sums(phy97.f.c.water) > 0, prune=TRUE)

phy97.f.c.sediment <- subset_samples(phy97.f.c,Coral_Species=="sediment")
phy97.f.c.sediment <- subset_taxa(phy97.f.c.sediment, taxa_sums(phy97.f.c.sediment) > 0, prune=TRUE)

# Transform sample counts to proportional abundance for downstream analyses
phy97.f.c.platy.p <- transform_sample_counts(phy97.f.c.platy, function(x) x/sum(x))
# Transform sample counts to proportional abundance for downstream analyses
phy97.f.c.fpenta.p <- transform_sample_counts(phy97.f.c.fpenta, function(x) x/sum(x))
# Transform sample counts to proportional abundance for downstream analyses
phy97.f.c.faviasp.p <- transform_sample_counts(phy97.f.c.faviasp, function(x) x/sum(x))
# Transform sample counts to proportional abundance for downstream analyses
phy97.f.c.faviam.p <- transform_sample_counts(phy97.f.c.faviam, function(x) x/sum(x))
# Transform sample counts to proportional abundance for downstream analyses
phy97.f.c.faviaall.p <- transform_sample_counts(phy97.f.c.faviaall, function(x) x/sum(x))
# Transform sample counts to proportional abundance for downstream analyses
phy97.f.c.water.p <- transform_sample_counts(phy97.f.c.water, function(x) x/sum(x))
# Transform sample counts to proportional abundance for downstream analyses
phy97.f.c.sediment.p <- transform_sample_counts(phy97.f.c.sediment, function(x) x/sum(x))

```


```{r, echo=FALSE}
# Save grouped data as RData file
save(list=c("phy97.f.clade","phy97.f.clade.p",
            "phy97.f.c","phy97.f.c.p",
            "phy97.f",
            "phy97.f.c.platy.p", "phy97.f.c.platy", 
            "phy97.f.c.fpenta.p", "phy97.f.c.fpenta", 
            "phy97.f.c.faviasp.p", "phy97.f.c.faviasp", 
            "phy97.f.c.faviam.p", "phy97.f.c.faviam", 
            "phy97.f.c.faviaall.p", "phy97.f.c.faviaall", 
            "phy97.f.c.water.p", "phy97.f.c.water", 
            "phy97.f.c.sediment.p", "phy97.f.c.sediment"),
     file = "C:/Users/Dani/Documents/Data_Analysis/KI_Platy/data/otus_97/KI_Platy_f_grouped.RData")
```

