---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source("http://bioconductor.org/biocLite.R")
library("Biostrings")
```

```{r}
mem <- read.table("membership_B.txt")
STJ2012 <- read.table("100_otus.tsv", sep="\t",check.names=FALSE,header=T, row.names=1, skip=1, comment.char="")

seqs <- readDNAStringSet("100_otus_rep_set.fasta")
names(seqs) <- gsub(" .*$", "", names(seqs))

for (cluster in levels(factor(mem$x))) {
  Cnames <- colnames(STJ2012.f)[mem$x==cluster]
  Cseqs <- subset(seqs, names(seqs) %in% Cnames)
  writeXStringSet(Cseqs, filepath=paste(cluster,".fasta",sep=""),append=FALSE,compress=FALSE,compression_level=NA, format="fasta")
  print(cluster)
  system(paste("R --vanilla < /Users/Danielle/Documents/Data_Analysis/KI_Platy/data/run_nw.R --args",
               paste(cluster, ".fasta",sep=""),
               "/Users/Danielle/Documents/Data_Analysis/KI_Platy/data/ITS2db_trimmed_derep.fasta"))
}


STJ2012.f

map <- data.frame(seq=colnames(STJ2012.f), clust=mem$x, col=mergedColors)
cols <- aggregate(data.frame(col=map$col), by=list(clust=map$clust), FUN=unique)

mod_otu <- aggregate(t(STJ2012.f), by=list(map$clust), FUN=sum)
mod_otu <- as.matrix(mod_otu[,2:ncol(mod_otu)])
mod_otu_rel <- apply(mod_otu, 2, function(x) x/sum(x))

png("barplot.png",height=4, width=10,units="in",res=300)
barplot(mod_otu_rel,col=cols$col)
dev.off()
graphics.off()


# Calculate topological overlap anew: this could be done more efficiently by saving the TOM
# calculated during module detection, but let us do it again here.
dissTOM = 1-TOMsimilarityFromExpr(STJ2012.f, power = 6);
# Transform dissTOM with a power to make moderately strong connections more visible in the heatmap
plotTOM = dissTOM^7;
# Set diagonal to NA for a nicer plot
diag(plotTOM) = NA;
# Call the plot function
sizeGrWindow(9,9)
# Set module colors
moduleColors = labels2colors(net$colors)
# Make network heatmap plot for all OTUs
TOMplot(plotTOM, net$dendrograms[[1]], moduleColors, main = "Network heatmap plot, all OTUs")

# Order correlations (TOMs?) and plot image
colnames(plotTOM) <- map$seq
rownames(plotTOM) <- map$seq
ordcor <- 1-plotTOM[order(net$colors), order(net$colors)]
image(ordcor)
# Get order of modules
mord <- net$colors[order(net$colors)]
# Get matrix of TOMs between module 1 and all OTHER modules
m1.bm <- ordcor[mord==1, mord!=1]
image(m1.bm)


hist(apply(m1.bm, MARGIN = 1, FUN=median))
head(m1.bm)
rownames(m1.bm)[rowSums(m1.bm) > 74]
median(m1.bm["denovo336356",])
colnames(STJ2012.f)
map
```