---
title: "KI_Platy_ms_notes"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

*JKB, 29 June 2017 - Before we proceed further, let's bullet point, our main findings as well as the prevailing views from the field. i.e. We need to very clearly lay out for a highly educated general audience what the expectation was for how corals would respond to heat stress and how what we found differs from the expectation. The expectation part needs to be greatly strengthened in the current draft i.e. we need to set up 'the mystery'*

*Here's what I see as the main discoveries:* 

1. Despite unprecedented heat stress, we show that some corals exhibited resilience and survived. Survival through such an extreme heat event provides an exceptional opportunity to understand how some corals can withstand intense heat stress, and how corals in general might survive long-term warming. Remarkably, we find that some coral colonies were able to survive this prolonged heat stress by regaining their symbionts while temperatures were still elevated.

2. After two months of heat stress, fully-bleached corals retained approximately the same *Symbiodinium* community as they had before the bleaching event. This suggests that a wholesale breakdown of symbiosis occurred in bleached corals during this event, indicating a lack of preferential symbiont expulsion or exodus.

3. Symbionts present in even very low abundances can play a critical role in coral survival and recovery. Some coral colonies recovered symbiosis with *Symbiodinium* types that were present in only a negligible amount before the bleaching event.

4. Local protection is critical for coral symbiosis and survival. Corals living at different levels of local human disturbance had distinct symbiont communities that corresponded tightly to survivorship. Our results suggest that some Kiritimati coral species may have the capacity to experience evolutionary rescue, defined as adaptation at a rate that allows an endangered population to survive the rate of environmental change (Orr & Unkless  2014, Carlson 2014). Our results suggest that the capacity for evolutionary rescue is tangibly related to local reef protection.


*Danielle to write out here a section of bullet points on - 'What is expected to happen to corals during heat stress?' (this can include bullets on prevailing viewpoints, bullets on observations from previous heat stress events or from this heat stress event in other locations (e.g. Hughes - GBR), along with the relevant citations).*

For example:
1. The prevailing viewpoint is that corals subject to elevated temperatures expel their symbionts and bleach.... (general statement here, including over what time period, and that they can recover their symbionts once the heat stress subsides). General points about the intensity / length /DHW that corals are thought to bleach at, are thought to survive through, or conversely thought to die from e.g. 'Corals do not typically survive more than X months of Y-Z degrees of elevated temperatures' - do we know what the most intense heat stress is that corals have previously been documented to survive through?

2. Prevailing viewpiont is that when coral colonies expel their symbionts, they preferentialy expel the sub-optimal ones. This typically means expelling symbions in Clade C. This has been shown in (explain studies....)

3. Prevailing viewpoint is that very rare symbionts are unstable and don't contribute much to coral colony fitness..... thus if corals are to survive heat stress it is generally believed that they either need to start with heat-tolerant D's being dominant (?, or at least quite common) or would need to acquire them from the surrounding environment. 
-Please confirm that we have the data from your water samples to show that those D's were not just floating around in the water column, but rather the only place they existed was in very very low #s within the colonies themselves?  

4. What is known / expected about local protection's influence on symbiont community? influence on survival through heat stress?

Danielle's Notes:  
  
1.	*Coral symbiosis is the foundation of coral reef ecosystems* [@Van_Oppen2006-qf; Muller-Parker2015-sd].  
  
2.	*The coral holobiont responds to environmental conditions, and is the unit that interacts with the broader reef community* [@Gates2011-zy]  
  
3.	*There is much genetic, functional, and response diversity within *Symbiodinium**  
Although *Symbiodinium* is a single genus, it contains diversity similar to diversity found within other dinoflagellate orders [@Rowan1992-lg], and is divided into nine clades and hundreds of types [@Van2005-di; @Franklin2012-sz; @Tonk2013-pf]. There is much debate about species classifications within *Symbiodinium*, which has hampered species naming within *Symbiodinium* [@Stat2012-gw; but see @LaJeunesse2001-hf) although *Symbiodinium* types are generally considered putative species [@Pochon2010-jm. *Symbiodinium* types have distinct geographic distributions, host associations, and environmental optima [@Fabina2012-mm]. Furthermore, total and relative abundance of *Symbiodinium* can vary among coral colonies, across environmental gradients, and over time [@Fitt2000-ex], with increased *Symbiodinium* abundance leading to increased environmental sensitivity and bleaching risk [@Cunning2012-um]. There are functional differences between *Symbiodinium* clades [@Stat2008-hk], and *Symbiodinium* associations can range from mutualistic to neutral to parasitic based on *Symbiodinium* type as well as environmental conditions [@Lesser2013-dj. Next-generation sequencing has revealed cryptic genetic diversity within symbiotic *Symbiodinium* [@Quigley2014-zj; @Arif2014-kx; @Green2014-az], and has allowed for long-term genetic and ecological comparisons of symbiont community structure [@Edmunds_undated-fd].  
  
4.	*Corals exhibit varying levels of symbiotic flexibility, but this flexibility comes with functional tradeoffs.*  
Corals that host flexible symbioses (generalists) may be more sensitive to environmental perturbations than those with intimate symbioses (specialists) [@Putnam2012-om]. Changes in photosynthetic efficiency during bleaching as well as bleaching resistance have been shown to correspond to distinct *Symbiodinium* phylotypes [@Kemp2014-xj]. Clade D *Symbiodinium* are proported to have an enhanced thermal tolerance [@Stat2010-zg], and repopulation of a coral host with clade D symbionts after a bleaching event is proposed to be a survival mechanism [@Berkelmans2006-rf; @Mieog2007-yy; @Silverstein2012-tm]. A history of thermal stress increased the prevalence of clade D *Symbiodinium* in a generalist coral species, but did not instigate similar changes in two specialist coral species [@Stat2013-qp]. Although the prevalence of clade D *Symbiodinium* increases during thermal stress and may increase thermal tolerance [@Berkelmans2006-rf], corals that house clade D symbionts may have slower growth rates [@Little2004-tm] or lower energy storage [@Jones2011-nf]. Furthermore, in an analysis conducted below the clade level, functional differences were found among types within clade C [@Sampayo2008-tw].
  
5.	*The adaptive bleaching hypothesis provides a testable hypothesis for bleaching causes and consequences, but hasn't found extensive support*  
The adaptive bleaching hypothesis suggests that corals bleach in order to expel environmentally sub-optimal symbionts, followed by switching (picking up new symbionts from the environment) or shuffling (an internal change in dominant symbiont type or overall symbiont community structure) [@Buddemeier2004-se; @Buddemeier1993-sx; @Baker2001-vc; @Baker2003-ks]. There is ample evidence for *Symbiodinium* shuffling (Rowan 2004), and a recent study showed evidence for *Symbiodinium* switching [@Boulotte2016-dy]. However, what remains unclear is if and how frequently bleaching events can actually be considered adaptive. net positive impact ?. ((Compare to gut microbiomes and extreme breakdown of this system?))

6.	*The current paradigm of coral bleaching and recovery states that the stress must cease for coral to regain their symbiosis*  
Coral bleaching is the loss of obligate symbionts (Symbiodinium) from the coral tissue [@Gates1992-ew; @Douglas2003-nr]. Thermal stress is the primary cause for coral bleaching, and can cause not only the breakdown of coral symbioses, but also cause coral mortality [@Hoegh-Guldberg1999-rb; CITE]. Thermal stress can be exacerbated by other environmental stressors (Cooper et al 2011, Béraud et al 2013, Maina et al 2008), and in turn, exacerbates ocean acidification (Gibbin et al 2015). The current paradigm of coral bleaching and resilience is that as environmental stress (such as warming) increases, corals begin to bleach. Extreme or long-lasting warming causes a complete breakdown of the coral symbioses, leading to expulsion of all (or nearly all) *Symbiodinium* from the coral host tissue. It has been shown that during bleaching, there is a window for recovery, that is, a certain amount of time during which the warming must cease and conditions must return to normal so that the coral can regain its symbionts. If the window for recovery passes without amelioration of the environmental conditions, the coral will starve and die. (Cunning et al 2016, Putnam et al 2017).  
  
7.	*Global coral bleaching is increasing, and the 2014-2017 event caused a catastrophic loss of corals around the globe.*  
There was up to 95% mortality in some regions during the 1997/1998 El Niño event (Glynn 1993). The 2014-2017 global coral bleaching event caused coral bleaching across the world's oceans (Eakin 2016, Normile 2016), with up to 75% bleaching on some reefs in Hawaii, and at least some level of bleaching across 93% of the Great Barrier Reef (Minton et al 2015, GBRMPA 2016). Despite these staggering losses, some corals have the capacity to be resilient to these increasingly frequent mass-bleaching events (Hughes et al 2017).   

8.	*There is evidence for local adaptation in corals* (Howells et al 2012, Logan et al 2013, Dixon et al 2015). Furthermore, in *Orbicella annularis* (a major Caribbean reef-builder), *Symbiodinium* biogeography correlates better with environmental patterns (i.e. chronic maximum summer temperature) than with coral host genetics (Kennedy et al 2016).
  
9.	*The "transient microbiome" assembled by environmental anomalies can undergo rapid changes (Putnam et al 2017), providing symbiotic stochasticity which may build or weaken a coral's capacity for resilience.*  
The "transient microbiome" assembled by environmental anomalies can undergo rapid changes (Putnam et al 2017), providing symbiotic stochasticity which may strengthen or weaken a coral's capacity for resilience. While corals have been shown to change symbiotic partners during a bleaching event (Chen et al 2005, Jones et al 2008), there is often a quick return to pre-bleaching *Symbiodinium* communities after recovery (Thornhill 2005, LaJeunesse et al 2010), and persistence of stress-related changes to *Symbiodinium* community structure may require sustained environmental pressure (Baird et al 2007). Corals commonly host background *Symbiodinium* types in low levels (Correa et al 2009), but sub-dominant *Symbiodinium* communities are often unstable (Coffroth et al 2010). The importance of rare *Symbiodinium* types is currently under debate, and these rare types may be commensal (pass through coral's holobiont with no harm or gain for either partner), parasitic ("cheaters", or symbionts that take more than they give), or mutualistic (symbionts which support host function) (Parkinson et al 2015). Some research suggests that low-abundance *Symbiodinium* types have minimal functional significance to corals (Lee et al 2016), while other evidence supports the idea that the rare *Symbiodinium* biosphere is important for corals' response to climate change (Boulotte et al 2016). However, shifts in *Symbiodinium* community diversity may still have a larger influence on coral resilience than the evolution of symbiont thermal tolerance (Baskett et al 2010). In other systems, other rare microbial species have been demonstrated to be disproportionally important to maintaining functional processes during environmental change (Shade et al 2014).
  
  
10. *Particulate and dissolved nutrients do not reduce coral health at a colony scale* (Rocker et al 2017) - (this result just seems crazy to me... also they considered the fact that corals at moderate WQ sites - which was their worst WQ - had fast growth, less-dense skeletons, high symbiont densities and high lipid content. This seems like a mixed bag to me. High symbiont densities make a coral more sensitive to bleaching (Cunning). I'm not sure if skeletal density is good or bad, except it's probably bad to have less dense skeletons during storms. They also found that dominant symbiont types differed among sites in one region (Burdekin) but thot the other (Whitsunday). Again, results & implications are a little unclear here as this isn't the major focus of their paper.)

  
FYI - probably don't include these points:
11. Eighty percent of coral species have horizontal symbiont uptake (Symbiodinium associations are formed anew with each coral generation from an environmental pool of symbionts)(CITE Nitschke Cites this statistic in abstract, but i'm having a hard time finding it. Other major paper on this topic is Baird et al 2009 ). Despite this, there is evidence for coevolution between coral and Symbidoinium (Thornhill et al 2014), although a Caribbean study showed that the structuring of host and symbiont populations were not congruent (Baums et al 2014).

12.	*Thick-tissue corals may be less susceptible to coral bleaching and mortality due to their tissue biomass and associated energy reserves.*  
Thick-tissue corals (such as Platygyra) may be less susceptible to coral bleaching and mortality due to their tissue biomass and associated energy reserves (Loya et al 2001). Furthermore, self-shading can protect "understory" *Symbiodinium*, those which reside deeper in the coral's tissue and consequently experiences less light stress, which can provide a symbiont reserve for repopulation and recovery (Kemp et al 2014).  
  
13. *Coral host gene regulation can influence *Symbiodinium* stress levels* Parkinson et al 2015 In a bleaching study with genetically different coral colonies and genetically similar *Symbiodinium*, symbionts that partnered with 'adaptive hosts', or those which altered the regulation of more genes during bleaching, were less stressed (Parkinson et al 2015). Indeed, coral transcription is correlated with the presence of different *Symbiodinium* genotypes (DeSalvo et al 2010), but it is unclear whether it is the host transcription or the *Symbiodinium* community that is the driver in this correlation.



Although *Symbiodinium* is currently classified as a single genus, it contains diversity similar to diversity found within other dinoflagellate orders [@Rowan1992-lg], and is divided into nine clades and hundreds of types [@Van2005-di; @Franklin2012-sz; @Tonk2013-pf]. There is much debate about species classifications within *Symbiodinium*, which has hampered species naming within *Symbiodinium* [@Stat2012-gw; but see @LaJeunesse2001-hf) although *Symbiodinium* types are generally considered putative species 

Furthermore, total and relative abundance of *Symbiodinium* can vary among coral colonies, across environmental gradients, and over time [@Fitt2000-ex], with increased *Symbiodinium* abundance leading to increased environmental sensitivity and bleaching risk [@Cunning2012-um].

Corals exhibit varying levels of symbiotic flexibility, but this flexibility comes with functional tradeoffs. Corals that host flexible symbioses (generalists) may be more sensitive to environmental perturbations than those with intimate symbioses (specialists) [@Putnam2012-om].

While corals have been shown to change symbiotic partners during a bleaching event (Chen et al 2005, Jones et al 2008), there is often a quick return to pre-bleaching *Symbiodinium* communities after recovery (Thornhill 2005, LaJeunesse et al 2010), and persistence of stress-related changes to *Symbiodinium* community structure may require sustained environmental pressure (Baird et al 2007). 