---
title: "KIPlaty_extra_text"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
*Titles should not exceed 75 characters (including spaces) for Articles. Titles should not include numbers, acronyms, abbreviations or punctuation. They should include sufficient detail for indexing purposes but be general enough for readers outside the field to appreciate what the paper is about.*
  
*Letters no more than 4 pages, of Nature. An uninterrupted page of text contains about 1,300 words.*

*Letters are short reports of original research focused on an outstanding finding whose importance means that it will be of interest to scientists in other fields. As a guideline they allow up to 30 references. They begin with a fully referenced paragraph, of about 200 words, (certainly no more than 300 words) aimed at readers in other disciplines. This starts with a 2–3 sentence basic introduction to the field; followed by a one-sentence statement of the main conclusions starting ‘Here we show’ or equivalent phrase; and 2–3 sentences putting the main findings into general context. See the information sheet 'How to construct a Nature summary paragraph' for an annotated example. The rest of the text is typically about 1,500 words long (not including Methods, summary paragraph or other sections). Letters have 3 or 4 small display items.*


Coral reefs, which already live on the edge of their thermal tolerance (CITE), are under acute threat from El Nino-associated ocean warming (CITE). The 2015/16 El Nino is the worst on record in terms of severity and longevity (@Eakin:2016vf), yet despite massive coral mortality, some corals show resilience to this extreme event. Corals form a nutritional symbiosis with unicellular algae (Symbiodinium) (Muscatine and Porter 1977). During thermal stress, this symbiosis deteriorates and Symbiodinium are expelled from the coral host, creating the characteristic white appearance of coral bleaching. *Need to emphasize the stress must decrease for symbiosis to be reestablished construct* *Variable capacity for recovery* Coral resilience is related to many factors (CITE), including the structure and flexibility of their internal symbiotic communities (CITE,CITE). However, the mechanisms of coral resilience to extended pulse stress events are still poorly understood. Here we show that corals have the remarkable ability to regain symbionts and recover during an extended stress event, providing hope for the future of coral resilience. Furthermore, we show that contrary to current opinion (CITE), symbionts present in miniscule abundances (<2%) are indeed important for coral recovery.
