---
title: "Untitled"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)

pdf(file = "figures/draft1.pdf",width=4, height=4) # Open a pdf that is 4x4 inches
phy97coral.f2.ad.before.platy <- subset_samples(phy97coral.f2.ad,Year!="2016March")
phy97coral.f2.ad.before.platy<- subset_samples(phy97coral.f2.ad.before.platy,Coral_Species=="Platygyra_sp")
coralsam <- phy97coral.f2.ad.before.platy
coralsam.ord <- ordinate(phy97coral.f2.ad.before.platy, "PCoA", "bray")
p1 = plot_ordination(phy97coral.f2.ad.before.platy, coralsam.ord, type="samples", color="Status", title="Symbiodinium communities",shape="Year") + scale_colour_brewer(type = "div", palette = "Set1", direction = -1) + geom_point(aes(size = 10)) #+ theme(legend.position="none")
print(p1)
dev.off()
```

```{r}
pdf(file = "figures/draft2.pdf",width=15, height=6) # Open a pdf that is 4x4 inches
# Subset samples to only look at coral 844
phycoral844 <- subset_samples(phy97coral.f2test,CoralTag=="844")
# Transform sample counts to proportional counts
phycoral844.p <- transform_sample_counts(phycoral844, function(x) x/sum(x))
# Make a bar plot
plot_bar(phycoral844.p,fill="hit") # this is a particularly good one
# Subset samples to only look at coral 99
phycoral99 <- subset_samples(phy97coral.f2test,CoralTag=="99")
# Transform sample counts to proportional counts
phycoral99.p <- transform_sample_counts(phycoral99, function(x) x/sum(x))
# Make a bar plot
plot_bar(phycoral99.p,fill="hit")
dev.off()
```

```{r}
pdf(file = "figures/draft3.pdf",width=15, height=6) # Open a pdf that is 15x6 inches
# Plot heatmaps for each time point
plot_heatmap(phycoral2014,taxa.label="hit")
plot_heatmap(phycoral2015a,taxa.label="hit")
plot_heatmap(phycoral2015b,taxa.label="hit")
plot_heatmap(phycoral2015c,taxa.label="hit")
plot_heatmap(phycoral20156a,taxa.label="hit")
dev.off()
```